public/ng/css/gogs.css, public/ng/less/gogs/repository.less
Prevent repository files table from overflow by a long commit message.
Before
After
=> Add max-width to commit message of repo-files-table

scripts/start.sh
This change to start.sh allows it to be executed from any working directory and always reference the gogs binary in the parent directory. Very helpful when calling start.sh from an init script.
=> Allow start.sh from any working directory

modules/avatar/avatar.go
Fixes a bug with the generation of addresses to download avatar.
For some reason, init() does not work.
2015/01/19 20:31:30 [D] avatar.fetch(fetch new avatar): http:39b285bb1127ed8bbc927e9690f74e19?d=retro&r=pg&size=200
2015/01/19 20:31:30 [T] avatar update error: Get http:39b285bb1127ed8bbc927e9690f74e19?d=retro&r=pg&size=200: http: no Host in request URL
=> Fix in url if cache avatar is enabled

templates/admin/config.tmpl
Fix error at admin/config (wrong var name in template)
```
template: admin/config:64:48: executing "admin/config" at <.DbCfg.SslMode>: SslMode is not a field of struct type interface {}
```
=> fix error at admin/config

public/ng/less/gogs/repository.less
Updated gogs.css to use monospaced font for sha hash label in repository view to make it look nicer because of equal label width.
Before:
After:
=> Updated gogs.css - monospace font for hash

.gitignore, public/ng/css/gogs.css, public/ng/less/gogs/repository.less, templates/repo/header.tmpl
Changed the repo-header-download-drop url input to behave slightly different. When clicking on the url input it now selects the whole url and you can copy it manually too. (When using a Flash Blocker for example.). Also I have replaced the Red Circle cursor (due to the default disabled class) with the default one. The behavior is now the same as on github.com.
Before:
After:
=> Changes to repo-header-download-drop

conf/locale/locale_en-US.ini, models/repo.go, modules/auth/repo_form.go, modules/middleware/repo.go, routers/repo/setting.go, templates/base/head.tmpl, templates/ng/base/head.tmpl, templates/repo/settings/options.tmpl
The normal go get protocol is to show the go-import meta tag when ?go-get=1 is appended to the url. This commit implements that behaviour and cleans the go-get option from the repository settings page.
=> Remove GoGet option from repository and handle it with ?go-get=1 instead

modules/base/template.go, modules/base/tool.go, templates/admin/auth/list.tmpl, templates/admin/org/list.tmpl, templates/admin/repo/list.tmpl, templates/admin/user/list.tmpl, templates/user/profile.tmpl, templates/user/settings/applications.tmpl, templates/user/settings/social.tmpl, templates/user/settings/sshkeys.tmpl
The "PHP" formatting function doesn't add anything, except an undocumented date format.
All usages in the templates have been replaced with DateFmtShort and DateFmtLong for convenience.
=> Remove the "PHP" style formatting function

modules/base/template.go, public/ng/js/gogs.js, templates/repo/diff.tmpl
Discussed with @phsmit about lines naming style and decide make it github-like, because there was a problem with 1 section 11 line in file and 11 section 1 line.
Now it looks like this: #diff-5922e0b56e4b93646193f3eac37b9202e646946dR1
Hash of file path, left or right and real line num in file.
=> The new new highlighting

cmd/web.go, modules/middleware/context.go, modules/middleware/repo.go, routers/api/v1/repo_file.go, routers/repo/issue.go, routers/repo/release.go, routers/repo/repo.go, templates/repo/header.tmpl, templates/repo/sidebar.tmpl, templates/repo/toolbar.tmpl
The boolean flags in the repo context have been replaced with mode and two methods
Also, the permissions have been brought more in line with https://help.github.com/articles/permission-levels-for-an-organization-repository/ , Admin Team members are able to change settings of their repositories.
=> Updating context and fixing permission issues

models/issue.go
According to the xorm logs, xorm ignores the num_issues and num_closed_issues columns when updating, even though the values did change.
This leads to wrong number of issues per label.
Listing the num_issue columns explicitly fixes the issue. 
However, we should consider just asking the DB for a correct count to fix existing, wrong counts. The query is basically instant for all use cases.
fixes #933 
\cc @Unknwon
=> Bugfix for wrong label count

docker/blocks/docker_gogs/Dockerfile, docker/blocks/docker_gogs_dev/Dockerfile
GOGS needs that binary to add a ssh key to a user
=> [docker] openssh-client provide ssh-keygen.

routers/user/home.go
This is a balance between speed and nice code, where speed has won. To prevent a repository query for each action the ownername is match with the current user.
It would be "cleaner" or "better" if we fetch the repository each time. Another option is to add the RepoOwnerID to action
=> Fix that owners also see actions on their repositories

models/action.go, routers/repo/issue.go
Instead of doing this on multiple places all over the place I've opt'd
to just fetching the correct issue counts from the database. This only
happens when calling UpdateIssueCounts()
should fix #933
=> Properly calculate the number of open issues per label

conf/app.ini, modules/mailer/mailer.go, modules/setting/setting.go
Some SMTP servers may be configured to check client certificate and do not accept arbitrary self-signed ones.
This pull request adds new keys to app.ini to specify cert and key files in the same way as for HTTPS certificate. Key names are the same as for HTTPS (CERT_FILE, KEY_FILE), so in the case there is a single certificate for both HTTPS and mail, it can be specified once in the default section of the app.ini.
=> Use client certificate for SMTP over TLS

Dockerfile, docker-compose.yml
Using this is easy:
1. Download & install `docker-compose` using instructions from here: https://docs.docker.com/compose/install/
2. Run `docker-compose up` from the project root
3. At the /install page, use "MySQL" for the database with the "root" user and "gogs" as the root password
That should be all you need to do to get running with Docker 1.5.0.
=> Project-level Dockerfile & docker-compose script

models/models.go
If the host setting looks like a unix socket (leading by char '/'), will use unix(host) as connection string
=> Add mysql unix socket support.

modules/middleware/auth.go
I have an URL containing a /git/ subdirectory for the service.
If I change LANDING_PAGE to explore, I'm redirected to /explore instead of /git/explore.
This patch add AppSubUrl to LANDING_PAGE.
=> Add setting.AppSubUrl for LANDING_PAGE = explore

scripts/init/centos/gogs
I tested the script in a Centos 6.6 server and it didn't work. Looks like `$!` didn't write the pid. After removing the use of pid it worked correctly.  
Also, the redirection should be `> ${LOGFILE} 2>&1` instead of `2>&1 > ${LOGFILE}` (see http://stackoverflow.com/a/637838/237761)
=> Remove use of PID and fix stderr redirection

conf/locale/locale_en-US.ini
choose should be in the past tense form of "chose"
=> Fixed minor gramatical error in the US install success msg

CONTRIBUTING.md
* Fix email contact in **Code of conduct** section. Change from *admin@gitlab.com* to  [Unknwon](https://github.com/Unknwon) email: u@gogs.io.
* The [CONTRIBUTING.md](https://github.com/drone/drone/blob/master/CONTRIBUTING.md) links from [drone](https://github.com/drone/drone) repository was dead. The file was deleted in a commit on June 2014. I've updated it with links from the last commit where the file exist.
=> Fix email contact and link

modules/asn1-ber/ber.go
It does not fix the real error behind the scene, but at least it prevent gogs from going into panic.
See https://github.com/gogits/gogs/issues/692
=> fixed panic error on user login

modules/middleware/context.go, routers/repo/http.go
Set `Content-Type` to `text/plain` for http status 401
This is because git command line shows the failure reason only if `Content-Type` is `text/plain`.
=> Set Content-Type to text/plain for http status 401

scripts/init/centos/gogs
We should be *sourcing* `/etc/sysconfig/gogs`, not *executing* it, don't we?
=> fix typo in centos init script

templates/explore/repos.tmpl
This simply changes the way the Explore page is displayed, allowing the viewer to see the author's name next to repository name.
=> Display author's name on explore page

cmd/serve.go
This simply changes the message that a user gets when connection via ssh without a given command from
> Hi user ! You've successfully authenticated, but Gogs does not provide shell access.
to
> Hi, user! You've successfully authenticated, but Gogs does not provide shell access.
[Plenks](https://en.wikipedia.org/wiki/Plenken) are evil ;)
=> Remove extra space from ssh authentication message

cmd/cert.go
Without a CN the self signed certificate is considered
invalid by chrome.
You can check with: openssl x509 -in cert.pem -subject -noout
Fixes issue #1231
=> Add CommonName to the self signed certificate

conf/locale/locale_de-DE.ini, conf/locale/locale_en-US.ini, conf/locale/locale_es-ES.ini, conf/locale/locale_fr-FR.ini, conf/locale/locale_ja-JP.ini, conf/locale/locale_lv-LV.ini, conf/locale/locale_nl-NL.ini, conf/locale/locale_pl-PL.ini, conf/locale/locale_pt-BR.ini, conf/locale/locale_ru-RU.ini, conf/locale/locale_zh-CN.ini, conf/locale/locale_zh-HK.ini, templates/repo/view_file.tmpl
The button appears when a file is viewed in a branch or a tag. It points
to a URL containing the branch's (or tag's) current commit id so that
it'll always point to the same content.
=> Add file permalink button

scripts/build.sh
On Windows, the executable name is `gogs.exe`
=> Update build.sh for Windows

scripts/systemd/gogs.service
Environment should be a space-separated list instead of comma-separated.
No need for double quoting when the values don't contain spaces.
http://0pointer.de/public/systemd-man/systemd.exec.html#Environment=
=> fix systemd "Trailing garbage, ignoring." warning.

scripts/init/debian/gogs
My git user has it's shell set to `/bin/false`, which makes `su -c` impossible, also a flag was misplaced and this fixes that the test run is executed as root. (#1025)
Disclaimer: I'm not an experienced Debian nor System-V init user, maybe someone could review this commit before it gets merged.
=> fix debian init script

packager/debian/postinst
Fixed an issue where the post intall file for Debian enforced port 6000
which should have been port 3000 because it renders the software virtually unusable
because it's a blocked port in Firefox, Chrome and alikes.
For further reference see:
http://www-archive.mozilla.org/projects/netlib/PortBanning.html
=> Fix: "Port is blocked" issue

modules/auth/user_form.go
If users are added to gogs due a reverse proxy automatically, their password is
set to their initial username. If their username is shorter than 6 characters,
they can never set a password. But since this password is required for some
operations (e.g. repository deletion), they could not use all features of gogs
until now.
=> settings/password: no minimal required characters for OldPassword

routers/user/home.go
This change fixes the output from /{{ username }}.keys so that it can work in
a ~/.ssh/authorized_keys file
=> fix .keys route

scripts/init/freebsd/gogs
I recently installed Gogs on a FreeBSD system and found that the provided init script refers to start.sh which does not exist any more (since 6c84223). This change gets it working again.
Thanks.
=> Fix command used by FreeBSD init script

templates/base/head.tmpl, templates/base/head_old.tmpl, templates/ng/base/head.tmpl
This commit disables the Referrer header normally sent by browsers.
Previously it was possible for private repo names, filenames etc. to be revealed to third-party sites. For example, if a readme or comment contained an external link then clicking on it would send the Gogs URL to that site. Users might not expect this to happen, especially for private repos.
The meta tag used here is part of the upcoming [Referrer Policy](https://w3c.github.io/webappsec/specs/referrer-policy/) spec. It's already implemented in Firefox and Chrome. (Chrome still sends referrers for embedded content such as images, but hopefully this will be fixed soon.)
Other options I considered were:
- Setting a Content-Security-Policy HTTP header, however the meta tag was simpler to implement.
- Setting a …
=> Prevent browsers from leaking referrer headers

models/repo.go, modules/cron/manager.go
Add function in cron to autofix counters in repository after erros in db
```
MariaDB [gogs_git]> select r.id, (select count(*) from star s where s.repo_id=r.id) as stars,r.num_stars,(select count(*) from watch w where w.repo_id=r.id) as watchs,r.num_watches from repository r limit 10;
+----+-------+-----------+--------+-------------+
| id | stars | num_stars | watchs | num_watches |
+----+-------+-----------+--------+-------------+
|  2 |     0 |         0 |      0 |           0 |
|  7 |     0 |         0 |      1 |           1 |
|  8 |     0 |         0 |      1 |           0 |
| 10 |     0 |         0 |      1 |           0 |
| 11 |     0 |         0 |      1 |           0 |
| 12 |     0 |         0 |      1 |           0 |
| 14 |     0 |         0 |      1 |           0 |
| 15 |     1 …
```
=> Add function in cron to autofix counters in repository

templates/user/issues.tmpl
```
template: user/issues:28:66: executing "user/issues" at <.Id>: Id is not a field of struct type *models.Issue
```
On the template we have to use ID instead of Id
The code sometimes use Id in some structures and ID in others. Even on same file like in `models/issue.go`. It is not something good and it is easy to make a mistake later.
=> User Issues Template fix

modules/base/template.go, templates/repo/home.tmpl, templates/repo/view_list.tmpl
This is a quick fix for #1137
`EscapePound` could be expanded to full blown url_encode probably using URL from `net/url` but I'm not sure how this will affect performance as it's a fairly frequently used function in templates.
Speaking of templates, every href attribute has to use `EscapePound` on user generated content i.e. various names (repo, user, directory, file) or risk invalid links.
=> Allow file and directory names to contain percent character

templates/repo/issue/list.tmpl
On repository issues page only show the pagination if needed. It is needed if one of the following conditions is true:
* It is not the first page (not IsFirst) because in that case is needed always.
* Or if we are in the first page (previous condition is false and that's why this second condition is evaluated, so it is the first page) and has more than one page (HasNext).
=> Show pagination only if needed on repo issues page

public/ng/css/gogs.css
This will solve the nested unordered list inside an ordered list issue. It is just a CSS error.
Issue: https://github.com/gogits/gogs/issues/1415
About the other problem reported about an ugly line appearing that is a blackfriday issue (so it must be reported to that library) or a blackfriday configuration issue (don't know if there is a blackfriday extension to solve that or other configuration that could be included in gogs that would solve that).
=> nested unordered list inside order list issue

modules/base/markdown.go, public/css/markdown.css, public/ng/css/gogs.css, public/ng/less/gogs/markdown.less
This is a new version of markdown less stylesheet inspired on github markdown styles.
I have enabled back the following blackfriday extension as it is with that extension enabled that the markdown looks the same than in github.
```
extensions |= blackfriday.EXTENSION_HARD_LINE_BREAK
```
I have not seen why it has been disabled. I can see the [commit](https://github.com/gogits/gogs/commit/81e6173356f94360217822b8104e6d3afac628b0) but I'm unable to find the reason.
This PR includes that change, the new `markdown.less` file and the resulting `gogs.css` file after compiling `gogs.less`. It includes `markdown.less` compiled into `markdown.css` too because in the issue pages `head_old.tmpl` is still used.
Should solve https://github.com/gogits/gogs/issues/1415 …
=> markdown styles tweaked

.gopmfile, modules/middleware/repo.go, public/js/app.js, public/ng/js/gogs.js, templates/ng/base/head.tmpl
I have added clipboard API support when available. First commit parses User-Agent header to add a class to html tag if the browser supports copy to clipboard. The second commit implements the javascript that copies directly to clipboard if the browser supports it or otherwise uses jquery zclip which uses an invisible flash to deal with the copy.
More details on https://github.com/gogits/gogs/issues/1396
Probably the minified version `public/ng/js/min/gogs-min.js` needs to be rebuilded.
=> Enhance copy clipboard

templates/repo/issue/view.tmpl
Fixed a bug where all comments on an issue would be marked as the "Owner" of the repository.
Before:
After:
=> Add check to see if comments on an issue are by the repo owner

models/user.go, templates/user/profile.tmpl
This hides the tooltips and links to configure your profile picture, unless it's your profile. This also links directly to the profile image, similar to how GitHub does, if you're looking at another user's profile.
Also included a commit to change the size of the resized uploaded avatars, from 200px to 234px, like was talked about in issue #1107. But not sure if this is how you wanted this fixed!
=> Hide avatar tooltips unless you're looking at your own profile

public/ng/css/gogs.css
Dashboard padding is 0 in left right and it would look alot nicer if they were 1.5em as the header, 1.5em is also a nice replacement for 24px top and bottom.
=> fix dashboard padding

public/less/_base.less, public/less/_repository.less, templates/repo/header.tmpl
Still not totally sure about the left part. So I maybe try a little more tomorrow. What do you think about this repo header?
Tomorrow I will set the breadcrumb to huge size again and add some padding to the left of forked from. I will review how it looks when mirror, repo and private.
=> modified repo header

templates/base/head.tmpl
Looks like a lot of changes but the only change is a new `.ui.grid` layer that contains the `.column` layer.
Because columns always belong to a `ui grid` and we forgot to include that layer.
All looks exactly the same after this change though there are some new margins and paddings that change nothing because they collapse in the same way than before the change.
Anyway for completeness this is needed and could lead to strange, not easy to debug, CSS problems if in future the semantic theme is changed.
=> column belongs always into a ui grid

routers/repo/download.go
423b1c69be7828c331a47467b66217d190e916b9, which in turn
causes all content to be served as text/plain. Let go decide
what the mime type is (e.g. text/html instead of text/plain).
=> 43bfee0d4872932c1da185e8367e21795bc4ceb5 reverted my change

.gopmfile
Fix Fail to load gopmfile: could not parse line: github.com/mcuadros/go-version
=> Fix Fail to load gopmfile: could not parse line: github.com/mcuadros/go-version

templates/admin/auth/edit.tmpl, templates/admin/auth/new.tmpl
Title pretty much says it all, the input box for the password field wasn't set to "type=password" so passwords were being displayed in plaintext on the screen. The change is pretty trivial.
Oops, changing to develop branch.
=> Change input field to type=password for the authentication templates.

modules/setting/setting.go, modules/user/user.go, routers/install.go
The same logic was duplicated in three places. Factor it
out in a single utility and improve it to also try
os/user.Current(). We need all the fallbacks because in
some cases it is better to not rely on the env vars, but
in other cases os/user.Current() fails with
"user: Current not implemented on linux/amd64".
=> Factor out function to get the current user

conf/locale/locale_en-US.ini, models/login.go, modules/auth/auth_form.go, modules/auth/ldap/ldap.go, routers/admin/auths.go, templates/admin/auth/edit.tmpl, templates/admin/auth/new.tmpl
The IsAdmin flag is set based on whether the admin filter
returned any result. The admin filter is applied with the user dn
as the search root.
In the future, we should update IsAdmin as well on each login.
Alternately, we can have a periodic sync operation.
=> Set IsAdmin using LDAP

public/ng/less/gogs/base.less
Seems to have a small problem because of the long language `Português do Brasil`:
This pushed down the rest, and ruined the 31px assumption. This just makes it wider so it doesn't run into that problem. Let me know if you run into any problems.
=> Updated - Lang Selection Width

models/repo.go
Set `repo.IsBare` true if the migrated repository is empty.
Closes #1588
=> Set IsBare true if migrated repo is empty

modules/base/template.go, templates/repo/diff.tmpl
This commit improves the way that commit messages are rendered, especially in the diff view. First, it fixes the 'diff' template so that the 'browse source' button correctly floats to the right of the message. Second, it renders line breaks and prefix spacing in commit messages.
Previously, when a commit message appeared in the log as:
```
Change 1 did this. Change 2 did this.
These changes were very good. I'm pretty happy with them. Here they are:
* Change 1
* Change 2
```
Gogs would render it is as:
```
Change 1 did this. Change 2 did this. These changes were very good. I'm pretty happy with them. Here they are: * Change 1 * Change 2
```
With this commit, Gogs will render the message just as it was in the log.
=> Commit messages now rendered with line breaks and prefix spacing.

modules/middleware/repo.go
Already described in the title. At the moment, if you do `go get` to a repo hosted on a gogs instance, you must use a lowercase username and repo name, otherwise it won't work, because gogs returns in the meta tag the username and the repo name in lowercase, and so `go get` finds two different names, and will just output to the user `package repo.url/username/reponame: unrecognized import path "repo.url/username/reponame"`.
=> Fix `go get` not working when there is a username or repository name with some uppercase letters.

scripts/init/debian/gogs
In testing startup on Ubuntu/Debian, it seems the `USER` environment variable is not present when Gogs is running using the default init script.
There may be a better way to fix this and make sure start-stop-daemon preserves the preconfigured environment, but I was at least able to complete installation (instead of getting an annoying `Run user isn't the current user: git ->` message (note the empty string for the 'CurrentUsername()' as picked up by the environment).
=> Set USER env variable so installation can complete successfully.

cmd/web.go, models/repo.go, public/ng/css/gogs.css, public/ng/less/gogs/repository.less, routers/repo/forks.go, routers/repo/stars.go, routers/repo/watchers.go, templates/repo/forks.tmpl, templates/repo/stars.tmpl, templates/repo/watchers.tmpl
The logic and templates are there and are accessible through their paths (/repo/stars, /repo/forks, /repo/watchers). It is however not implemented in the repo's UI.
=> Implemented #1721: see users who forked/starred/watched a repository

.dockerignore, Dockerfile, docker/build.sh, docker/s6/.s6-svscan/finish, docker/s6/gogs/run, docker/s6/openssh/run, docker/sshd_config, docker/start.sh
This is a complete rewrite of the current Gogs docker container.
Some stuff was bothering me like the size of the container or the fact that we could not use localhost to connect to linked database.
I've rewrite it for this purpose while implementing other stuff that people wanted
This PR provide the following:
- New container base on `alpine:3.2` making the base container lighter
- S6 as system init and process supervisor (does not require a scripting runtime and pretty straightforward to configure)
- A build script for the application, this help with the size of the container as only one layer is created when the application is compiled. This script install building dependencies, compile the software and then remove those dependencies. The resulting layer then only contains the app …
=> New approach to Gogs Docker Container

.dockerignore, Dockerfile, docker/README.md, docker/s6/gogs/run, docker/s6/gogs/setup, docker/s6/openssh/run, docker/s6/openssh/setup, docker/start.sh
- Now using a setup script before starting the app. The separation of the run script and the setup script will make service initialization a little bit clearer
- Now calling start.sh script as ENTRYPOINT and S6 as CMD. This way when running the container with just a shell script, the start.sh script will be launched before, making debugging easier
- Added note about `.dockerignore` ignored during Docker Hub Automated Build
=> Docker Container: Init 1 & Initialisation

.gitignore, Dockerfile, docker/s6/.s6-svscan/finish, docker/start.sh
- Fix s6 fifodir error on container restart, cleanup is done twice
- On start so that the issue does not happen when container is killed  via `docker kill`
- On stop so the resulting stopped container is clean if accessed by other means
- Add .tags* to .gitignore (Atom auto ctags generation)
=> Docker Container Restart Fix

docker/s6/gogs/setup, docker/s6/openssh/setup, docker/start.sh
- Fixes #1759 
- Volumed subfolder now created up in the ENTRYPOINT script, this way
they are created before S6 even starts making VOLUME.
- The subfolder will be created during VOLUME creation too as ENTRYPOINT
script will be run before /bin/true
- SSH Keys will now be created on a single key basis not replying on the
existence of /data/ssh folder
=> Volumed data setup changed to allow #1759

docker/s6/gogs/setup
- resolve #1765
- create link to old git repository path: `/home/git/gogs-repository` for backward compatibility
=> Docker repository path backward compatibility fix

docker/s6/openssh/setup
- ssh/setup: test directive now check if a file exist in key path instead of a folder
- ssh/setup script was hanging waiting for an input about rewriting the key as the test case was returning true, when it should have been false (check if file is a folder instead of a file)
=> Fix bug introduced in #1759 preventing ssh server to launch

conf/locale/locale_en-US.ini
"Enable this to disable..." is needlessly confusing, simplify it by being
upfront that this setting disables the Gravatar fetching.
=> Simplify disable Gravatar preference wording

modules/setting/setting_memcache.go, modules/setting/setting_redis.go
Hello,
After re-compiling gogs with Redis from the master branch today, I wasn't able to run gogs. The error message was "panic: cache: unknown adapter 'redis'(forgot to import?)"
It's a minor issue with new go-macaron path.
Kenno
=> Fix import path

docker/start.sh
- `start.sh` will now verify that the port is not already used by another service when creating an `socat` link
- Log when a `socat` service is created, or could not be created making debugging easier with linked containers
- Keep track of which port is already used, including goes & sshd port to prevent collision
- Resolve #1807
=> Update docker `socat` link creation

modules/auth/repo_form.go
For some reason, the field names for Private and Mirror got swapped.
This causes private non-mirror migrations created through the API to end up public, and public mirrors to end up private.
=> Fix the JSON field names for MigrateRepoForm

modules/middleware/repo.go, templates/base/head.tmpl, templates/ng/base/head.tmpl
This makes Gogs repos work with godoc.org: https://github.com/golang/gddo/wiki/Source-Code-Links
=> Add go-source directive to repo pages

conf/app.ini, models/publickey.go, modules/setting/setting.go
This patch moves the, currently hard coded, minimum key sizes into the configuration file. This way it is possible to enforce company security standards in gogs. For example it is now possible to disable DSA support or enforce RSA keys with a higher minimum length.
This also makes it possible to easily support new key formats as the only place which has to be adjusted is the configuration file.
=> move minimum key sizes to config

scripts/init/freebsd/gogs
The gogs_directory is not necessarily the same as the HOME directory.
WIthout this gogs ends up writing the authorized_keys file at  $gogs_directory/.ssh/authorized_keys which is not always the right place for it.
=> HOME fix into FreeBSD init script

conf/app.ini, modules/middleware/context.go, modules/setting/setting.go, templates/base/footer.tmpl, templates/ng/base/footer.tmpl
This allows the admin to disable the version information about gogs and
go in use in the footer.
This fixes #1957.
=> fix #1957 - disable version display

conf/locale/locale_en-US.ini, modules/git/utils.go, templates/user/dashboard/feeds.tmpl
The hyperlink and the display name of the branch if the branch is in a folder or the branch name has '#'
I didn't commit modules/bindata/bindata.go, you need to re-generate and commit it.
Fix #1965
**Bug Example**
I setup a branch like the issue said at https://try.gogs.io/john.doe/project_x
And I had add your account to the collaborator, you can see what listed below on the dashboard afte you logined:
```
john.doe pushed to #1965 at john.doe/project_x
ceb578ba4e Initial commit
bfd5a61610 Initial commit
```
=> Fix #1965 - the hyperlink and the display name of the branch

cmd/dump.go
fixes includes:
* adding error handling on the target dump creation
* using a temporary directory to create the db and repositories dumps
* using the proper setting.<dir> instead of setting.workDir() for log/ and custom/
* adding few logs for tmpdir handling
* adding the name of the generated archive in  the final log
It fixes some weird behaviors where if the log/ and custom/ are not in a path relative to the gogs binary directory and if the command is not run from this directory, **gogs dump** will fail silently and create an empty archive.
=> various fixes in gogs dump command

modules/middleware/org.go, routers/user/home.go, templates/org/home.tmpl
This is follow-up for 56c66ee486b4b8d544201662de62a23f36e6a069 allowing admin
to see private repositories, even when not being member of them.
Without this patch, admin is effectively unable to edit any organization, so is not really an admin.
(this is rebased to `develop` PR #2054)
=> Admin should be able to see all organizations

templates/user/dashboard/dashboard.tmpl
This adds the button to create a new mirror on the dashboard at the same
place where "new repository" and "new organization" already exist.
This solves #2037.
=> add new mirror button to dashboard

public/css/gogs.css, public/less/_base.less, public/less/_octicons.less, public/less/_repository.less, templates/repo/commits.tmpl, templates/repo/commits_table.tmpl, templates/repo/forks.tmpl, templates/repo/header.tmpl, templates/repo/home.tmpl, templates/repo/issue/labels.tmpl, templates/repo/issue/list.tmpl, templates/repo/issue/milestones.tmpl, templates/repo/release/list.tmpl, templates/repo/release/new.tmpl, templates/repo/settings/collaboration.tmpl, templates/repo/settings/deploy_keys.tmpl, templates/repo/settings/githook_edit.tmpl, templates/repo/settings/githooks.tmpl, templates/repo/settings/hook_new.tmpl, templates/repo/settings/hooks.tmpl, templates/repo/settings/options.tmpl, templates/repo/sidebar.tmpl, templates/repo/view_list.tmpl, templates/repo/watchers.tmpl, templates/repo/wiki/new.tmpl, templates/repo/wiki/pages.tmpl, templates/repo/wiki/start.tmpl, templates/repo/wiki/view.tmpl
This is rebased to develop version of #2064 (thanks to GitHub for not allowing to simply changing PR base :imp:)
This patch improves experience, making Octicons and repo file list look better. 
* Ensure Octicons are used with 16px font size
* UI: Mark top menu icons blue only when non-zero
* UI: Gray SHA1 next to message, file list collapse
I can understand that changing SHA1 label color to gray may be arguable, but I believe that this make the whole UI more balanced and less aggressive-looking. I believe that colorful labels should be reserved either for tags or issue types.
See below for latest screenshots.
=> Repo file list layout & misc fixes

public/css/gogs.css, public/less/_repository.less
This removes remains from old design, that was not cleaned by previous #2068 PR.
=> UI: Remove CSS rule making last-commit SHA bold

public/css/gogs.css, public/less/_repository.less, templates/repo/commits_table.tmpl, templates/repo/view_list.tmpl
Current green SHA1 labels are more pronounced than other UI elements attracting attention as if they were most important thing in the UI, while they are not as important, especially without real Git client.
Using grey SHA1 labels makes the UI more balanced, less aggressive and lets user to focus on other content elements.
NOTE: Neither GitHub or Bitbucket uses so heavy pronunciation as Gogs. (they are also not using SHAs on file list, that's why showing commit lists below)
This was previously proposed by #2068 and supported by @Depado.
I know there are supporters of current green SHA1 label look, and many users that are used to them. But they are also ppl that may find them distracting and actually repellent, that is why I humbly ask for concrete arguments behind having green labels and …
=> UI: Use more subtle grey SHA1 labels

modules/template/template.go, public/css/gogs.css, public/less/_base.less, templates/repo/commits_table.tmpl, templates/repo/diff.tmpl, templates/repo/view_list.tmpl
Most commit in Git are expected to follow standard of single header line,
followed by description paragraphs, separated by empty line from previous block.
Previously Gogs were treating everything as single header. Now we are trying to
render only first line as header, but following lines (description chunks) as a
verbatim.
=> Render commit msg as header + verbatim description

modules/git/hooks.go
This hook can be used for example to reject too large commits and it is
executed before "update" hook, used exclusively by Gogs to update its state.
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
=> Allow pre-receive hook customization

public/js/gogs.js, templates/repo/branch_dropdown.tmpl, templates/repo/commits.tmpl, templates/repo/home.tmpl
We break the branch-chooser dropdown from the repository homepage into its own template and also call it from the commits page to allow for the selection of a branch/tag to view.
=> Dropdown on commits page to choose branch #1846

Makefile
This is achieved by adding public/css/gogs.css to special .IGNORE target, which
makes inability to generate/update gogs.css non-fatal and not stopping whole
build process. User is still notified about missing lessc command though, since
inability to update CSS may lead to potential problems:
lessc public/less/gogs.less public/css/gogs.css
make: lessc: No such file or directory
make: [public/css/gogs.css] Error 1 (ignored)
More info at:
https://www.gnu.org/software/make/manual/html_node/Special-Targets.html
=> Makefile: Do not fail build on missing lessc

gogs.go
=> gogs: add import that lets gogs run as a stand-alone windows service

templates/admin/auth/edit.tmpl, templates/admin/auth/new.tmpl
LDAP via BindDN bind_dn and bind_password parameters are optional. They may be left blank to perform an anonymous search.
=> LDAP parameters UI: bind_dn and bind_password are not required

cmd/serve.go, conf/app.ini, modules/setting/setting.go
Local (DMZ) URL for gogs workers (such as ssh update) accessing web service. In
most cases you do not need to change default http://localhost:HTTP_PORT/. You
may need to alter it only if your ssh server node is not the same as http node,
eg. running behind proxy on different node than web server.
--- 80 public port -> 8080 -- web server node
/
public proxy --<
\
--- 22 public port -> 10022 -- ssh server node
This option is not intended to be accessible via web GUI settings, since it is
unlikely someone needs to change it to somethings else than default
http://localhost:HTTP_PORT/ which should work for most of the cases.
But this should land into the documentation somewhere.
=> LOCAL_ROOT_URL for workers accessing web service 

modules/ssh/ssh.go
I was trying to use built-in ssh server from an OSX client and I couldn't push, it didn't even log an error. I added some debug code and found that it was unexpected ``env`` pushed.
```
2015/12/13 06:04:33 [I] [env]: payload LC_CTYPEUTF-8' replaced LC_CTYPEUTF-8' args: '[]string{"\bLC_CTYPE\x05UTF-8"}'
2015/12/13 06:04:33 [...s/modules/ssh/ssh.go:62 func·001()] [E] len(args) 1 != 2
```
I found the reason:
SSH: `SSH-2.0-OpenSSH_6.9`
OS: OSX El Capitan
`/etc/ssh/ssh_config` file from OSX (I guess, I didn't put that there myself):
```
Host *
SendEnv LANG LC_*
```
This pull request just log invalid env arguments instead of silently return.
=> Ignore invalid env for SSH Server (OSX fix)

models/user.go
We set the default value for the non-NULL field `NumFollowing` of the User model to 0, which stops an error when the ORM tries to sync.
=> Add default for NumFollowing field (fixes #2261)

Dockerfile.rpi
The Dockerfile.rpi (Raspberry / ARM Version) pointed to the old path for the s6-vscan command. As a consequence, docker run without providing a custom command fails.
This pull request corrects the path by applying the change in the Dockerfile from https://github.com/gogits/gogs/commit/0cbf56855aad82ff49952132287a0112f308c728 to the Dockerfile.rpi as well
I successfully built a container from the corrected version of Dockerfile.rpi (based on V0.8.10)
=> Update s6 path in Dockerfile.rpi

public/css/gogs.css, public/less/_base.less
Simple trick to prevent the page from "jumping" when navigating from/to a page not long enought to have the scroll.
=> Making scroll always visible.

docker/s6/openssh/setup, docker/sshd_config
Since OpenSSH is configured for using protocol version 2, it's worthless the generation and use of RSA1 keys.
Building a Docker container using rpi version, OpenSSH 7.1 is used and due to a bug on this version RSA1 keys generation is broken and you'll get errors:
`Saving key "/data/ssh/ssh_host_key" failed: unknown or unsupported key type`
`Could not load host key: /data/ssh/ssh_host_key` 
Anyway, cloning via SSH seems to work fine.
Building a Docker container with normal version, OpenSSH 6.8 is used and there are no errors.
=> Remove RSA1 keys as only SSH version 2 is used

scripts/init/freebsd/gogs
If the init script is called with `status`, the rc.subr(8) routines check if
the first argument associated with the pid in the pidfile is equal to
`procname`. By default, `procname` is equal to the value of `command`. In our
case, `command` contains a space (i.e. has multiple arguments), so `procname`
can never be equal to the first argument of the command associated with the
pid.
Set `procname` to the first argument of `command` to fix the `status` command
of the init script.
=> Fix status command in FreeBSD init script

templates/repo/view_list.tmpl
This is fixup for ea375c0dcca118c8ac3c48ba569b025836ad5ccf. The bug was not
visible because commit.RefUrl was always returning empty url due regression
described in https://github.com/gogits/git-module/pull/4
=> commit.RefUrl expects AppUrl argument

scripts/launchd/io.gogs.web.plist
Using this script:
1. Copy scripts/launchd/io.gogs.web.plist into `/Library/LaunchDaemons`
2. The script assumes Gogs is running under `gogs` user and group, modify `/Library/LaunchDaemons/io.gogs.web.plist` if you want to user different user.
3. The script assumes Gogs is installed in `/Users/git/gogs`, modify `/Library/LaunchDaemons/io.gogs.web.plist` if you installed Gogs in different location.
4. Once you are sure that running Gogs manually via `gogs web` works fine, run it as a launchd service with:
sudo launchctl load -F /Library/LaunchDaemons/io.gogs.web.plist
From now on launchd will ensure Gogs is running, eg. when system is restarted.
=> OS X launchd script

routers/user/profile.go, templates/user/profile.tmpl
Added Organization images to profile (Fixes #2332)
Fixed "Follower" Icon too big (Changed class from "user" to "octoicon-person"
Before: ![](http://i.imgur.com/jLKfqKP.png)
After: ![](http://i.imgur.com/SVpic8i.png)
(We needed this in our organization. So I figured I push our changes to the official git ;))
=> Added organization display on profile

modules/ssh/ssh.go
According to the docs [1], the Reply method must be called for all
requests where WantReply is true. This fixes a hanging java ssh
implementation (jsch) which sets WantReply flag and waits for reply from
the server.
[1] https://godoc.org/golang.org/x/crypto/ssh#Request.Reply
=> Fix #2431 - handle requests waiting for reply

Makefile
`make test` will run the test files for all the packages.
`modules/httplib` is failing. But, if we can fix it, it would be a good idea to configure the CI to run the tests.
=> Add command to run the test suite in Makefile.

models/webhook.go
As title says, fixes #2465
```
git@debian-gogs:~/gogs-repositories$ echo "select length(url) from hook_task;" | mysql -uroot -p gogs
Enter password: 
length(url)
255
972
```
=> Fixed Webhook URL-length Issue #2465

models/pull.go, models/user.go
This PR fixes issue #2495.
Changing the name of a user breaks some links on the Pull Request pages.
- 500 Server Error on the "Files changed" tab (URL: `/:user/:repo/pulls/:id/files`)
- 404 Not Found on the "Commits" tab when you click a revision number of a commit
This PR replaces all occurrences of the old user name in the table `pull_request` with the new one.
=> Change user name in Pull Requests to avoid errors (fixes #2495)

Dockerfile, Dockerfile.rpi, docker/build.sh
This PR consist of small changes to both `Dockerfile`, `Dockerfile.rpi` & `docker/build.sh` which consist pretty much of an update of the container base system and a fix from a previously introduced bug.
- `Dockerfile`:
* Base image is now alpine:3.3 making the community repository availlable to stable release (pinning will not be needed to update go to its latest version)
- `docker/build.sh`:
* A bug was introduced in #2475 by using a virtual package to manage build-depencies as repository pinning was not compatible with it. This bug made apk fetch the mainstream version of `go` in `x86` build which was 1.4.2 instead of 1.5.3. It was also preventing the `RPi` container to build as `go` was not present in the `main` repository.
* Going from `alpine:3.2` to `alpine:3.3` fixes this problem …
=> Update Docker container with Alpine 3.3 & Fix RPi2 build

models/org.go, routers/user/profile.go
*Re-PR of #2523 because of wrong branch.*
---
Previously, the profile page of an user showed all organisations the user owned (regardless if public or not), which makes no sense. After merging this, the profile page will show all organisations the user has joined (not just the one's he owns), except the private (=not public) one's. Just like on GitHub :-)
=> Show all orgs on user profile, except the private one's

templates/explore/repo_list.tmpl, templates/user/dashboard/dashboard.tmpl
Makes more sense, because private repositories still do have the yellow background.
**Before**:
**After**:
=> Use icon repo-forked instead of repo-lock for private, forked repos

public/js/gogs.js
Looks like I missed something in #2538. Markdown code block syntax highlighting did still not work when updating an issue description or comment. Is fixed now.
**Before**:
**After**:
=> Fix syntax highlighting for markdown code blocks on issue description/comment save

cmd/web.go
Works: `/compare/sha1...sha1`
Works: `/compare/sha1FOOsha1` <-- make this don't work anymore
---
Side note:
Actually, I was trying to make [7-digit sha1 sums](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1) work, but I failed, because you can't make a Hex from an odd length string ([here](https://github.com/gogits/git-module/blob/3c8c495/sha1.go#L86)).
Another thing: I really wonder why gogs does not use [libgit2](https://libgit2.github.com) (like GitHub, BitBucket, etc.). Is that on purpose?
=> Escape unescaped periods in route regular expression

cmd/web.go, models/org.go, modules/middleware/context.go, modules/middleware/org.go, routers/org/teams.go, routers/user/home.go
Users should only be able to see repositories & teams they can access / they have joined. Right now, a user sees all repositories of an organization but when he clicks on it, a 404 page comes up. After merging this, users will only be able to see the teams & repos, they have access to. Just like on GitHub & Co. :-)
Explanation of screenshot:
```
User left:
- is Owner of org2
- can see all repos
- can see all teams
User right:
- only in Team2
- can see public repos
- can see repos of Team2
- can see team Team2
Anyone:
- can see public repos
```
=> Hide other teams & repos from organization page

public/less/_repository.less
Added small arrows pointing to user avatars similiar to github
Example:
=> Add small arrows on issue comments pointing to users avatar

models/issue.go, routers/repo/issue.go
fixes #2563 
There were actually _two_ bugs. First, it parsed the user-input as UTC and converted it to local-time when saving to the database, then, when loading it treated it (again) as UTC and converted it to local-time.
=> fixes #2563

models/admin.go
Fix #1738
I tested and it is working properly. The folder is really deleted and I could create another repo with the same name.
=> Workaround delete folder on Windows.

models/git_diff.go, models/git_diff_test.go, modules/template/highlight/highlight.go, public/css/gogs.css, public/less/_base.less, routers/install.go, routers/repo/commit.go, routers/repo/pull.go, routers/repo/view.go, templates/repo/diff_box.tmpl
=> Enable syntax highlighting on diff view

modules/auth/ldap/ldap.go
This is fix-up for 573305f. Forgot to fetch AttributeUsername value from the
LDAP server, so the setting was effectively not working as intended.
=> Fix #2221 LDAP username attribute must be fetched

templates/repo/header.tmpl
Adds an or condition to the **Commits** tab so that the `active` class is enabled when viewing commit/diff pages
=> Make commits tab active when on diff page

conf/app.ini, modules/setting/setting.go, modules/template/template.go, templates/base/head.tmpl
Used by Android >= 5.0 to make the top bar colored.
Reference: https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android
Before:
After:
=> Implementing the "theme-color" meta tag.

docker/s6/crond/run, docker/start.sh
- add the crond initscript for s6
- add the RUN_CROND configuration variable to setup crond
- `crond will` not be run by default (hence the `down` file in the service directory)
- `start.sh` check if RUN_CROND = `true` || `1` and remove this file to tell s6 to run the initscript
- test container is availlable @ `quay.io/0rax/gogs`
- permit the addition of custom cron job by mounting your crontab in `/var/spool/cron/crontabs/`
- you can also add cron script to `/etc/periodic/(15min|hourly|daily|weekly|monthly)/`
- resolves #2597
=> Add the ability to run crond inside the Docker container

models/org.go, routers/user/profile.go, templates/user/profile.tmpl
This is inspired by @Unknwon 's post in #2571 
The only thing left to do is let org admins see the private repos as well. And maybe get a yellow outline or something on the avatar
=> Admins and user itself sees private org relations on profile

cmd/web.go, models/repo.go, modules/middleware/repo.go, routers/repo/issue.go, templates/repo/header.tmpl, templates/repo/settings/options.tmpl
Allow to fork and disallow to create PRs for mirrors, which addresses issue #2505.
Changes have been made to handle cases of prior created mirror repositories to provide backwards-compatibility.
Pull Requests were disabled, because...
1) Mirrors are supposed to be read-only (merging a pull request would write to the it).
2) prior to this change, no forks could have been made from within the GUI, making Pull Request support redundant.
=> #2505 Allow to fork and disallow to create PRs for mirrors.

Dockerfile
Eliminates some package-manager wrangling which has become unnecessary since the Dockerfile was written (~half a year ago, targetting alpine 3.2). In particular, by eliminating the edge pin, we're a bit more insulated from possible breaking changes in edge (package upgrades in stable are not supposed to be breaking).
- s6 is in main in 3.3, so we no longer need to mangle the repos file
- official image is periodically updated, so it's not preferred to do
upgrades downstream (usually harmless, but inelegant)
- apk-tools in 3.3 supports --no-cache to avoid leaving the APKINDEX
files in the image
=> Dockerfile cleanup for Alpine 3.3

public/css/gogs.css, public/less/_repository.less
Currently attachments in issues are stretched into their 150x150px box - most of the time this looks fine but for long, non-square or icons ize images this can soon look untidy and pixelated
I have made CSS changes to change them to look like this:
=> Image attachments keep aspect ratio

templates/repo/pulls/tab_menu.tmpl
Adding the same condition to the pull request tabs that the main tabs have.
Before
After
=> Change colour of numbers on pull request tabs if greater than zero

templates/repo/wiki/view.tmpl
=> Hide the download archive button when viewing wiki pages

.github/ISSUE_TEMPLATE.md
I've noticed that a lot of issues cannot be reproduced on http://try.gogs.io,
which either hints about specific database type problems or
hints about bugs which are already solved in the newer version
(as http://try.gogs.io is usually a newer build).
This patch adds the suggestion to test the issue at http://try.gogs.io in
the Github "issue template". The user can answer: "Yes", "No", "Not relevant".
"Not relevant" is an option where testing on http://try.gogs.io makes no sense as
the bug is unrelated to the Web UI or is very specific in nature.
=> ISSUE_TEMPLATE: suggestion to test at try.gogs.io

models/repo.go, templates/repo/header.tmpl
Addresses #2588
Will show something like forked from joshfng/gogs instead of forked from subpath/joshfng/gogs
=> Use relative url when showing forked from

cmd/web.go, models/user.go, routers/org/setting.go, routers/user/setting.go, templates/org/settings/options.tmpl
Implements #2763.
I created a new DeleteAvatar() method in the User model. Both settings router (user and org) uses this method.
Because the 'Enable Custom Avatar' option is not present in the org's settings form, after deleting the org's avatar no new custom avatar is generated, the default Gravatar picture is displayed (https://secure.gravatar.com/avatar/?s=100). Does this needs a fix? May I include the option in the org's form too, or generate a random avatar after deleting the previous?
=> Added: Ability to delete org avatar.

routers/user/home.go
Now with the proposed solution by @Unknwon.
=> Allowing site admins to view private repositories in org/home

models/access.go, models/issue.go, models/issue_comment.go, models/release.go, models/repo.go, routers/repo/repo.go
Using mysql/5.7.11 and a new installation from deploy branch 5267dce21023802818b0c0c16ba2ca47c146e1b5 , various pages show error page 500.
Navigating to the dashboard will give:
```
.routers/user/home.go:123 Dashboard()] [E] GetRepositories: Error 1054: Unknown column 'updated' in 'order clause'
```
To reproduce:
1. Pull the latest develop branch (5267dce21023802818b0c0c16ba2ca47c146e1b5)
1. Create a new database
1. Install, configure gogs, login as user
1.  Try to navigate to the dashboard
I've investigated a bit and found a change was introduced in ad513a20e939691828ba415c9a565e8ff3daa95f that migrated all `updated` and `created` fields to `updated_unix` and `created_unix`.
Checking out a commit before ad513a, gogs will work without issues.
On clean databases the original fields …
=> Update uses of updated and created

templates/base/head.tmpl
Use the authors name, and the description of the repo in HTML meta.
Pages without repository context will display as before. This implements #2670.
=> Set HTML meta values corresponding to repository

Makefile
This allows the user to specify build flags from the make command
line. For example to force a complete rebuild one could use:
make BUILD_FLAGS='-v -a' TAGS="sqlite"
=> Make go's build flags a variable

modules/markdown/markdown.go
Replace spaces with "%20" in "urlPrefix", before markdon processing.
The spaces were causing blackfriday (markdown processor) to behave
strange. This fixes #2545 (hope it works this time...)
=> Fix relative links in markdown files

templates/base/head.tmpl
Set the description meta tag correctly when there is no repo
description. Also use the  ability to trim trailing whitespaces,
to make the template cleaner.
This cleans up the current code, and fixes [moltam's](https://github.com/moltam) comment in #2670.
=> Set description meta tag correctly

models/user.go
Make user search function look in username (lower_name), full name
(full_name) and primary email (email). This will benefit searching after
user in "explore", admin panel and when adding new collaborators.
As i see it, there are no security issues regarding searching for the primary email and full name. Both are already a part of the users public profile.
This implements #2814, but somehow also #2792.
=> Make user search look in username, name and email

templates/org/home.tmpl
=> Display org member's full name in link title.

public/css/gogs.css, public/less/_repository.less
Using a monospace font, makes editing easier (e.g. tables, code).
=> use monospace font for wiki and issue textareas (fix #2869)

models/issue.go
It's a start as a followup to https://github.com/gogits/gogs/issues/2892
=> Try to make the SQL queries cleaner and more secure

public/js/gogs.js
I noticed that there was a large delay when loading a file in the web interface before the line numbers displayed. This PR does not remove the delay, but it does improve it slightly.
This PR reduces the on load event handler time from ~700-900ms to ~70-90ms.
To verify my timings:
Use the Chrome developer tools "Timeline", reload the page. Mouseover the 'load' Event to see the timing.
Note that I am seeing a lot of fluctuation in the timings between refresh, but my changes are consistently <100ms, and the original is consistently >700ms
=> Reduce line number creation to one DOM manipulation

conf/license/ISC license
New one from Wikipedia and https://opensource.org/licenses/ISC.
I think the original one is for code owned by the Internet Systems Consortium.
=> Update ISC license

docker/README.md
As request in [discuss](https://discuss.gogs.io/t/document-socat-link-and-its-relevance-with-kubernetes/228), i've updated the docker documentation to include more information about our container options such as `SOCAT_LINK`:
- Created a `Container options` section in `docker/README.md`
- Added documentation for `SOCAT_LINK`
- Moved `RUN_CROND` documentation to this new section
=> Update Docker documentation about container options

conf/locale/locale_en-US.ini, models/repo.go, models/repo_test.go, modules/auth/repo_form.go, modules/markdown/markdown.go, modules/markdown/markdown_test.go, routers/repo/setting.go, templates/repo/settings/options.tmpl
Allow to use alphanumeric issue mentions (e.g. ABC-1234) for external links.  This works specifically with JIRA and Bloodhound.
=> Fixes #2669: Allows alphanumeric issue style for external issue tracker links

models/admin.go
- Prevent panic on creating notice if database is not available
- Prevent incorrect folder on Windows (`/` instead of `\`)
=> Fix remove folder issues, including initialization failling

README.md, README_ZH.md
Hello, i'm the creator of [DPlatform](https://github.com/j8r/DPlatform), that aims to make it easy to install self-hosted applications.
I really like your Git service, so I added its support to my project.
I would like to add a link to it on your main page, so that other people can easily install Gogs on their Linux servers.
=> Add DPlatform as an installation way

glide.lock
Need to use latest version of gogits/go-gogs-client with Team support
=> Update glide.lock with latest go-gogs-client

.dockerignore, Dockerfile, Dockerfile.rpi, docker/build.sh
- docker/build.sh will now use glide to fetch dependencies
- glide is built from source to keep compatibility with arm (no pre-prebuilt binary for arm)
- docker/build.sh will also now use the provided Makefile. 
It will generate an error when trying to get git build hash as we do
not ship the 88mo .git directory during the build (should not cause
any problem as the variable it sets was not set previously)
- Updated gosu to 1.9 in `Dockerfile` & `Dockerfile.rpi`
- Tested on OSX (Docker for Mac), Raspberry Pi 2 (ArchLinux) and Raspberry Pi 3 (HypriotOS / Raspbian Jessie)
=> Update docker/build.sh script to use glide & make

modules/auth/ldap/ldap.go
From https://godoc.org/crypto/tls#Config
ServerName is used to verify the hostname on the returned
certificates unless InsecureSkipVerify is given. It is also included
in the client's handshake to support virtual hosting unless it is
an IP address.
This is needed for certificate validation without InsecureSkipVerify.
=> Add ServerName to tls.Config in LDAP auth

public/css/gogs.css, public/less/_repository.less
Hidden labels on an issue still have some padding, meaning labels move slightly further down as the amount of labels increase.
Before
After
=> Fix empty space surrounding hidden issue labels

conf/locale/locale_en-US.ini, templates/user/profile.tmpl
Do not assume avatar needs be changed from gravatar.com
Always send user to settings screen to change avatar.
Drops "change_custom_avatar" localized message, keeps "change_avatar"
for the generic one.
=> Do not assume avatar needs be changed from gravatar.com

models/action.go
use 'official' repo.Name instead of incoming repoName; to enforce correct capitalisation
=> Fix capitalisation of repo-name in news

models/error.go, models/token.go, modules/auth/auth.go, routers/repo/http.go
Fixes security issue #3110 by checking if sha token is empty and returning error in this case
=> Fixes security issue #3110

modules/markdown/markdown.go, modules/markdown/markdown_test.go
Markdown module is now more strict about what URLs it interprets as issue and commit URLs.
The main change is that it now checks to see if the URL starts with the `setting.AppUrl` before treating it as an issue or commit URL.
=> Fixes #3006: Markdown misinterpreting issue URLs

conf/app.ini, conf/locale/locale_en-US.ini, models/git_diff.go, modules/setting/setting.go, routers/repo/commit.go, routers/repo/pull.go, templates/repo/diff_box.tmpl
Today Gogs supresses the whole diff when it is too big. I dislike it, because I can't see anything about the commit other than the message. I have no tip about what files changed.
This PR makes Gogs supress diffs per file, like GitHub does. It looks like this (I hardcoded this case):
So now `MAX_DIFF_LINES` sets the max lines per file (I changed the default to 500).
I am open to suggestion if someone dislike this change.
To-Do:
=> Re-work MAX_DIFF_LINES: supress diff per file, not the whole diff.

conf/app.ini
QQ STMP host port is 465
host = smtp.qq.com:465
and need the Authorized
=> port 25 do not work, and port 465 is right

modules/setting/setting.go
change  setting.go -> LocalUrl  value default to  `sec.Key("LOCAL_ROOT_URL").MustString(Protocol + HttpAddr + HttpPort + "/") `  
issue #3077  
=>   change  setting.go -> LocalUrl default value  to MustString(string(Protocol) + "://localhost:" + HttpPort + "/")

models/models.go
For reference, Issue #2972. 
Beforehand, any DSN parameters on MySQL or Postgres databases would cause an error due to the concatenated strings not checking if parameters already exists. 
getEngine() now checks for existing parameters and correctly address the additional strings being concatenated for the databases according to whether a parameter exists. User may enter `database name` with or without parameters now. 
This helps for certain databases that require specific configurations, such as MySQL databases using `old_passwords=1` with the `allowOldPasswords=1` argument being passed to the DSN.
=> getEngine() now handles DB parameters (#2972)

Dockerfile, Dockerfile.rpi
supersedes #3250 
When I am providing timezone to a container via the TZ environment variable, it isn't getting picked since the `/usr/share/zoneinfo` (`tzdata` package) is missing.
This causing 2 hours difference in the container's logs.
Below is the evidence showing this behavior:
```
host $ docker exec -ti gogs bash
bash-4.3# echo $TZ
Europe/Amsterdam
bash-4.3# date                                                                                                                                          
Sun Jul 10 08:48:12 GMT 2016
bash-4.3# apk add tzdata
(1/1) Installing tzdata (2015g-r0)
Executing busybox-1.24.2-r0.trigger
OK: 40 MiB in 32 packages
bash-4.3# date
Sun Jul 10 10:49:30 CEST 2016
```
=> docker: Support timezones

conf/app.ini
Turkish language name changed to 'Türkçe' from 'Türk' because 'Türk' meaning is 'Turkish People' in Turkey but 'Türkçe' meaning is 'Turkish Language'.
=> Changed Turkish language name to 'Türkçe'

models/webhook.go
This fixes #3169 
As per https://api.slack.com/incoming-webhooks ("Handling errors") the response body is undefined and should therefore not be checked.
=> Ignore Response Body for Slack Hooks #3169

models/user.go
Fixes relative urls coming from api/v1
See https://github.com/drone/drone/issues/1701
=> Return avatar link as absolute url

routers/api/v1/api.go, routers/api/v1/repo/hook.go
Allows the deletion of a webhook from a repository at the
/:user/:repo/hooks/:id endpoint.
Solves drone/drone#1603.
Signed-off-by: Dennis Chen <barracks510@gmail.com>
=> api: delete repository webhooks

models/issue.go
This resolves #3180 by adding table aliases to the Issues SQL statement.
Once the 500 error was gone, I discovered another bug where the open/closed counts always showed 0 when viewing the same type of issues.  This was also fixed by adding table aliases to the Issues Stats statement.
=> Fixes #3180: 500 error when attempting to view issues of type 'Mentioning you'

routers/repo/setting.go
Proposed fix for #3228.  ctx.Repo.Mirror is refreshed following a repo name change.
=> Fixes #3228: Error on changing repo name when the repo is a mirror

models/user.go, modules/avatar/avatar.go
Sets all avatars to use PNG image format.
Keeps avatars consistent at 290x290px resolution.
Signed-off-by: Dennis Chen <barracks510@gmail.com>
=> avatar: make custom and generated avatars equal

models/git_diff.go, templates/repo/diff_box.tmpl
Git determines submodules as files with file mode 160000. I retreived the file mode from git output and added appropriate field `IsSubmodule` to `DiffFile` struct. Also I disabled view file button on UI for submodules like on github
=> Fixes #2407 View diff file on submodule gives a 404 page

models/release.go
The `NewReleasePost` function always uses the `form.Target` parameter when
quering the repo for the commit to use. That is sufficent when creating a
release based on the current `HEAD` of a branch but if one would want to
create a release based on an already available tag the release page will
link to the current `HEAD` instead of the appropiate tag commit.
Let's check the given `form.TagName` if it exists and use that tag commit
for the new `release` entry.
You can observe the faulty behavior at the https://try.gogs.io/nalla/test-repo2/releases page. Have a look at release 1. The original valid commit link [`c4b66f39ec`](https://try.gogs.io/nalla/test-repo2/commit/c4b66f39ecc83f592545c336c27d95def62bb3c0) was replaced with the current head commit …
=> routers/repo/release: Check tags when adding release

templates/repo/issue/list.tmpl
If anonymous (not signed in user) requests page "/:owner/:repo/pulls" he gets an error:
```
template: repo/issue/list:11:105: executing "repo/issue/list" at <.PullRequestCtx.Base...>: nil pointer evaluating *models.Repository.Link
```
This pull request fixes that.
=> Fix of template error in "/:owner/:repo/pulls"

public/css/gogs.css, public/less/_repository.less
Small visual change to file icon colors:
=> Lighter icon colors for repo files

.github/CONTRIBUTING.md, README.md, README_ZH.md, docker/README.md, routers/install.go, scripts/windows/install-as-service.bat, templates/base/footer.tmpl, templates/base/head.tmpl, templates/home.tmpl, templates/repo/settings/hook_gogs.tmpl
Nice you use HTTPS on your website, so now only the links to your website need to be updated.
=> Replace gogs.io http links with https version

models/release.go, routers/repo/release.go
Like Github, release note now using the tag creation date rather than the web release note creation date (Issue #3315). If tag does not exist yet, last commit on selected branch will be used.
=> Fix #3315: Release dont use tag creation date

conf/app.ini, models/git_diff.go, models/git_diff_test.go, modules/setting/setting.go
1) Try to reduce memory allocations
2) Add possibility to disable diff highlight (can improve performance for large diffs)
3) Tweaking with cost for prettier (cleaner) diffs
4) Do not calculate diff when the number of removed lines in a block is not equal to the number of added lines (this usually resulted in ugly diffs)
Examples for 3:
- [Before](https://cloud.githubusercontent.com/assets/7011819/17458691/267b2dec-5bf1-11e6-83bd-7ddd3b44695e.png) - [After](https://cloud.githubusercontent.com/assets/7011819/17458692/3696e752-5bf1-11e6-927a-2aaee9a79e3a.png)
- [Before](https://cloud.githubusercontent.com/assets/7011819/17458695/46950c24-5bf1-11e6-87eb-f924bd82a3c5.png) - [After](https://cloud.githubusercontent.com/assets/7011819/17458697/52679558-5bf1-11e6-9852-ad88cc2621b5.png)
- …
=> Improve diff highlight

models/action.go, models/update.go, routers/api/v1/convert/convert.go, routers/repo/webhook.go
This PR contains the following changes:
-Fixes the bug mentioned in #3271 where the committer is listed in the author information on API calls
-Expands both the API and Webhooks to include committer user information
-Include usernames for both authors and committers (this was enabled for Webhooks, but not for the API)
This PR depends on gogits/go-gogs-client#40
=> Add committer information to API and Webhooks. Also fixes #3271

conf/app.ini, models/repo.go, modules/setting/setting.go
This pull request add new key on `app.ini` to configure the mirror global interval (#3398).
By example, to set mirror global interval to 6 hours rather than 24 :
```
[mirror]
GLOBAL_INTERVAL = 6
```
=> Feature #3398: Redefine global mirror interval

models/org.go
Fix issue when user want leave an organization (issue #3379) and don't have repositories.
Fixed by just adding a check before using the SQL statement IN who can't be used with empty list.
=> Fix #3379: syntax error at or near

modules/markdown/markdown.go
This pull request fix issue #3420: when the same commit tag is referenced more than one time on a single message, generated link are not valids.
```
2eb7f261c1502b6f8981267f6c142f4563da5f37 or 2eb7f261c1502b6f8981267f6c142f4563da5f37
```
=> Fix #3420: Bad commit reference URL generation

models/pull.go
Fix for #3396.  AddTestPullRequestTask needed to be called from PullRequest.Merge.
=> Fix for #3396 - Pull request conflict status not updating properly

cmd/web.go, modules/setting/setting.go, routers/admin/admin.go, templates/admin/config.tmpl
Rename key `CacheInternal` with `CacheInterval` (issue #3430).
=> Fix #3430: Typo on cache interval setting key

conf/locale/locale_en-US.ini, templates/repo/issue/view_content.tmpl
The "Sign in to comment" link is good enough and will correctly
show or not show the "Sign Up" button link for those not having
an account already.
Fixes #3407 (link to nowhere when registration is disabled)
=> Do not show the "Sign up for free" button in issue tracker

templates/base/head.tmpl
WIP
This is an attempt to fix #3089 following the strategy introduced
in d625e41c6c4d40fadbeaf99dd97e77aa0c9085ae, although that strategy
by itself does not seem to be sufficient.
What needs be done is honouring the redirect_url query parameter
from the auth router.
\cc @Unknwon
=> Always set redirect_to on header-provided sign-in

routers/api/v1/api.go, routers/api/v1/repo/collaborators.go
Adds the `PUT /repos/:username/:reponame/collaborators/:collaborator` endpoint, based on https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator, allowing the API to add collaborators to a repository.
I messed up #2775 (it was opened on the wrong branch).
**EDIT**: now implements `permission` like github's api, taking one of three arguments, "pull", "push" or "admin".
I can squash into one commit if that is prefered.
=> Add AddCollaborator API Endpoint

routers/api/v1/admin/user.go
Allows to edit the MaxRepoCreation of a user through the `PATCH /admin/users/:user` endpoint.
I messed up #2774  (it was opened on the wrong branch).
=> Add MaxRepoCreation to EditUser API

cmd/web.go, routers/repo/release.go
This pull request aim to fix issue #3314 with non flat tagname (ie: release/x.x.x) leading to a 404 error when user trying to edit it.
I have used this solution rather than using `EscapePound` because replacing _/_ with _%2F_ seems not working. Macaron still treat _%2F_ as _/_ before process routing and finally returning a 404 error (I don't even reach the function EditReleasePost(ctx *context.Context, form auth.EditReleaseForm).
__Demonstration:__
https://try.gogs.io/zero-x-baadf00d/psychic-soul/releases/edit/release%2f1.3.1
I'm not sure is a good idea, for URI readability and SEO, to use url encoding on path components. It legit fo query string arguments, but not sure for path.
=> Fix #3314: Cannot edit release with tag name contains slash

cmd/web.go, conf/app.ini, modules/setting/setting.go
Initial support for unix sockets. I have tested it on Arch Linux, but would be nice with some more testing. Right now you have to use `HTTP_ADDR` to set the location of the socket. It would definitely be better to rename it to something like `LISTEN_ADDR`, or creating a `UNIX_SOCKET_ADDR`. 
Issue #2217
=> Add initial support for unix sockets

cmd/web.go, modules/base/tool.go, modules/markdown/markdown.go, modules/markdown/markdown_test.go
Short commit references now working with a 7 to 40 SHA length'  (Issue #3321) and base.ShortSha() function has been modified to uniformize short SHA's representation (length: 7).
=> Fix #3321: commit tag shortener

cmd/web.go
This HTTP header tells the browser the filename it should use for downloads.
Today, if you open an image attached in an issue and hit `CTRL+S` to save, the default name would be something like `3adb8e12-4df8-44d4-bba8-d989ea16e58f.jpg`.
With this change, it should be the original filename, something like `my-image-file.jpg`.
=> Add Content-Disposition header for attachment downloads

models/models.go
This PR add ability to handle IPv6 address with PostgreSQL (issue #3437). Now `HOST` can be filled with:
- `HOST = 127.0.0.1:5432`
- `HOST = 127.0.0.1`  // Use default port
- `HOST = [::1]`
- `HOST = [::1]:5432`
- `HOST = /tmp/pg.sock`
- `HOST = /tmp/pg.sock:5342`
_Tested on CentOS 7 with PostgreSQL 9.5_
=> Fix #3437: Cannot connect to PostgreSQL via IPv6 address

templates/admin/auth/new.tmpl
Fix #3450: For the "Tip" when adding Authentications it says "Post" 587 instead of "Port" 587
=> #3450: fix grammar + typo.

cmd/dump.go
Permission mask of created dumps are now 0600 (-rw-------) rather than 0644 (-rw-rw-r--). As @waldiTM say on the issue #3361,  dump files include private information like database credentials and repositories, access must be limited.
=> Fix #3361: Dumps are created world readable

models/issue.go
Fixes #3486 
Label-data is stale, so we have to fetch Issue-data again before sending it...
(Please feel free to suggest a better idea :laughing: )
=> Fix PR-webhook issue where Label-data is stale (#3486)

models/webhook.go, routers/api/v1/repo/hook.go
The pull_request event for webhooks was not supported when creating/updating webhooks via the API, this is a fix for that.
=> added support to set pull_request event from api

models/issue_label.go
This patch fixes the order of display labels (Issues #3189  and #3445). Now they are ordered by name rather than ID (primary key).
=> Fix #3189: Sort labels by name

models/repo.go
Git convention has it capitalised, this triggers a lot of OCD in some people.
=> Fixed typo

conf/app.ini, modules/setting/setting.go, modules/template/template.go, templates/base/footer.tmpl
This pull request add a new option (`SHOW_FOOTER_LOAD_TIMES`) to toggle on/off the footer load times information (Issue #3492).
**Extract from app.ini**
```
[other]
SHOW_FOOTER_BRANDING = false
; Show version information about gogs and go in the footer
SHOW_FOOTER_VERSION = true
; Show load times
SHOW_FOOTER_LOAD_TIMES = true
```
=> Feature #3492: Add option to hide footer load times

public/css/gogs.css, public/less/_dashboard.less
I'm not totally sure whether this is the best way to tackle this issue. However, this PR fixes repo list displays for OSX on Safari, making them consistent with other browsers (issue #2875).
Dashboard without fix:
Dashboard with fix:
Profile without fix:
Profile with fix:
=> Fix repo list display on Safari (fixes #2875)

models/models.go
---
The newest version of xorm changes the xorm.Engine interface where the Where, is no longer `Where(string, ...interface{}) *xorm.Session` but instead `Where(interface{}, ...interface{}) *xorm.Session`. However, xorm _**[still supports string queries](https://github.com/go-xorm/xorm/blob/master/statement.go#L139-L162)**_.
I've read somewhere that the string query may be deprecated and removed soon, so this fix may or may not be a permanent solution, thus it is best to slowly convert existing database queries to use go-xorm/builder.
=> [HIGH PRIORITY] Fixed Xorm V6 compile errors

routers/user/auth.go
This small hot-fix is basically a very cheat way of showing a successful 'confirmation email' sent to the email even if it does not exists.
Well, by allowing users to see if an email exists breaks a very fundamental law of security through obscurity. This small patch just forces Gogs to show a confirmation page even if the user does not exist.
=> Forces a confirmation page on 'Forgot Password' page even if user does not exist

models/issue_comment.go, routers/api/v1/api.go, routers/api/v1/repo/issue_comment.go
This implements Deletion of Issue-comments and Listing all issue-comments in a Repo
https://developer.github.com/v3/issues/comments/#delete-a-comment
https://developer.github.com/v3/issues/comments/#list-comments-in-a-repository
Edit: Closes #3673 
See gogits/go-gogs-client#48
Adds 2 new Endpoints:
Issue Comments are ordered by ascending ID.
```
GET /repos/:username/:reponame/issues/comments
```
| Name | Type | Description |
| --- | --- | --- |
| since | string | Only comments updated at or after this time are returned. This is a timestamp in RFC3339 format: `2006-01-02T15:04:05Z07:00` |
```
Status: 200 OK
Content-Type: application/json
```
``` json
[
{
"id": 74,
"user": {
"id": 1,
"username": "unknwon",
"full_name": "无闻",
"email": "u@gogs.io",
"avatar_url": …
```
=> More Issue-Comments API-endpoints

scripts/init/gentoo/gogs
init script for gentoo
place it into `/etc/init.d` directory
then run `service gogs start` or `/etc/init.d/gogs start`
=> init.d script for Gentoo Linux

conf/locale/locale_en-US.ini, modules/base/tool.go, routers/repo/view.go, templates/repo/view_file.tmpl
This pull requests adds support for video files using the HTML5 video tag. This allows viewing videos files directly in the webinterface - essentially the same way PDF files are supported.
Video files are not ideal to be managed using git, but may be stored in repositories as part of a projects documentation. This is the case in a project I am currently working on, and it helps a lot being able to preview these files directly in gogs instead of having to download and to open them in a video player. With video support in most of the current browsers (http://caniuse.com/#search=video) this seems like a helpful feature to be implemented in gogs.
=> Support for video files using the HTML5 video tag

models/migrations/migrations.go, models/org.go, models/user.go, models/user_mail.go, modules/base/tool.go, routers/admin/users.go, routers/api/v1/admin/user.go, routers/install.go, routers/user/auth.go, routers/user/setting.go
This PR fixes the following issues:
- The random string generator was [modulo-biased](https://stackoverflow.com/a/10984975).
- The random string generator silently ignored any errors returned by `rand.Read`. In the worst case, `GetRandomString` would simply return an empty string.
=> Fix random string generator

models/user.go, modules/base/tool.go
Don't know why we'd want to duplicate something which already exists in `golang.org/x/crypto/pbkdf2`
=> Don't use custom PBKDF2 function

modules/auth/ldap/ldap.go
TGis request try to fix #3791 
As https://msdn.microsoft.com/en-us/library/aa366101(v=vs.85).aspx describe spaces should not be in start or at the end of username but they can be inside the username. So please check my solution for it.
=> #3791 update LDAP username check

modules/auth/ldap/ldap.go
According to https://tools.ietf.org/search/rfc4513#section-5.1.2 LDAP client should always check before bind whether a password is an empty value. There are at least one LDAP implementation which does not return error if you try to bind with DN set and empty password - AD.
=> Check for zero length passwords in LDAP module.

conf/app.ini, modules/setting/setting.go, modules/ssh/ssh.go, routers/install.go
Mostly security reasons.
There should be an option to make a builtin SSH server listen on the specified network interface. Currently it uses **0.0.0.0** only. If somebody has several network interfaces: to the Internet, to the intranet, to the localhost etc. - Gogs shouldn't open a service to the Internet without any options.
You could say "There is no shell", but it is still a service and every service potentially is vulnerable.
I've added some code changes to make it configurable and **0.0.0.0** by default like HTTP server.
=> New settings option for a custom SSH host

modules/template/template.go, routers/repo/editor.go, templates/repo/wiki/view.tmpl
Very simply, this pull request modifies certain files to escape symbols in filenames that may cause 404s unescaped.
This solves issues #3666 and #3674.
=> Escaping '?' symbols in filenames

models/issue.go, models/issue_comment.go, models/issue_mail.go
UpdateIssueUsersByMentions was calling database write operations while
a transaction session was in progress. MailParticipants was failing
silently because of the SQLITE_LOCKED error. Make sure failures in
MailParticipants enter the log, and pass on the transaction context.
Addresses #3760.
issue: let caller pass in database context, and use it
issue_comment: obtain database context to pass to UpdateIssueMentions
issue_comment: log any error from call to MailParticipants
issue_mail: pass on database context to UpdateIssueMentions
=> Fix database write context interleaving bug

cmd/web.go
Related to the issue #3743, this pull request fix the regex used on the route file for SHA and branches comparisons.
- A SHA hash can only contains `a b c d e f 0 1 2 3 4 5 6 7 8 9`
- A branch name could be smaller than 7 characters
=> Fix #3743: Fix SHA and compare regex on route file [Critical]

conf/locale/locale_en-US.ini
Other locales appear to use the plural version, and the text is being associated with more than one statistic.
=> Pluralize "Statistic" for English locale to be consistent with others

.pkgr.yml
This enables building a package for Ubuntu 16.04 LTS (Xenial) as suggested in #1263. I seriously have no idea why bzr and mercurial are needed as build dependencies, but the build only proceeds with them; I got the idea from the packager.io go example project.
The build succeeds: https://packager.io/gh/gianperrone/gogs/build_runs/8#71773
I have a test installation running and found no problems.
=> Enable Ubuntu 16.04 build at packager.io

conf/app.ini, modules/setting/setting.go
INI file doesn't support array format with bracket "[]",
It may be better to use ',' to split it.
=> fix bug #1122 log.smtp receiver configure error

modules/markdown/markdown.go
The following changes are made to the way cross-repository issue references are handled:
-Short references can be used now e.g., `gogits/gogs#24`
-Rendering also includes the repo reference (addresses #2960). This applies to both short references and full URL references
=> Improve cross-repository issue references in markdown

routers/repo/http.go
Not perfect but I think it's a reasonable solution.
For small request bodies, I suppose performance wouldn't be an issue.
For large ones, this seems to be a necessary evil.
Fixes #636
=> Use temporary file to avoid out-of-memory when receiving big chunks.

public/js/gogs.js
Change Javascript regular expression to match non-latin characters
The regex comes from here: http://stackoverflow.com/questions/150033/regular-expression-to-match-non-english-characters#comment22322603_150078
And this patch should fixed these two issues: #3919 #3843
=> Fix wrong anchors for non-latin headings

conf/app.ini, modules/setting/setting.go
Enabling federated avatars by default makes it easier to be nice with users who have their own avatar distribution setting.
=> Enable federated avatars by default

gogs.go
Since Go 1.5 GOMAXPROCS is already set to the number of CPUs in the system. This call will also be removed from Go in the near future (part of their plans once they feel the scheduler is good enough) so I thought it'd make sense to remove it here.
=> Remove call to set GOMAXPROCS

Dockerfile.aarch64
Minimal changes compared to `Dockerfile.rpi`, you may find and test an already built docker image
[here](https://hub.docker.com/r/atzoum/aarch64-gogs/).
=> Dockerfile for aarch64 (odroid c2 & pine64)

models/mail.go, modules/setting/setting.go
I think that this fix and close #3659 #3856 #3714 #3615
It works in better form than PR #3960 cause pick the FROM addess in case of you have some like `FROM = "My Fancy Gogs" <git@noreply.lan>` in cofig,
=> Fix notification email issues

routers/api/v1/repo/file.go
This pull request adds a simple check for bare repositories before retrieving raw files. If the repository is indeed bare (There are no branches or commits), just return a 404.
This fixes #3992.
=> Verify repository is not bare before retrieving blob (Fixes #3992).

models/user.go
The time taken is a function of the length of the slices and is independent of the contents.
* https://golang.org/pkg/crypto/subtle/#ConstantTimeCompare
=> Safe compare password (timing attack)

Makefile, scripts/build_linux64.sh
This will output a position independent executable. A few benefits to this:
- While normally used as a hardening technique to better take advantage of ASLR (thus making exploits harder), this doesn't really have the same effect on Go binaries since everything is bounds checked and (hopefully) has no dangling pointers underneath. Still, this can help if any code calls out to unsafe code (C/C++) and can potentially help guard against situations where there may be a hole in the Go runtime (probably never the case).
- A lot of distros are now requiring packages to be shipped as PIE executables.
Note that this setting won't work on Windows or OS X so I'm assuming that the Makefile will never be used on Windows.
=> Produce a position independent executable

routers/repo/commit.go, routers/repo/middlewares.go, routers/repo/pull.go, routers/repo/view.go
Creating a notice instead
Fixes #3643
=> Fix 500 when repo has invalid .editorconfig

cmd/serve.go, modules/setting/setting.go
Check if the deploy key can access to a repository. A deploy key
doesn't represent an gogs user, so in a site with Service.RequireSignInView
activated we should give read access only in the repositories where
this deploy key is in use. In other case, a deploy service or system
using an active deploy key can get read access to all the repositories
in a Gogs service.
=> Check deploy keys when Gogs is run with Service.RequireSignInView=true

templates/base/footer.tmpl
The copyright date in the footer was still set to 2016.
=> Change copyright date to 2017

public/assets/librejs/librejs.html, templates/base/footer.tmpl
https://github.com/gogits/gogs/issues/4084 I've finished the librejs template file, but I need some help with routes. 
I'm not sure how do templates routes work and I don't want to make something wrong. I'm trying to make gogsbaseurl.com/librejs to contain the LibreJS page, but can make it work and I'm afraid to break something. Once that is done, I'll have no problem adding a link to the footer template. Could one active/experienced programmer in this project help me?
Sorry for my ignorance, I never programmed in Go and I'm having a hard time in understanding how the code works.
=> Add LibreJS support

models/migrations/migrations.go, models/models.go, modules/setting/setting.go, public/js/gogs.js, routers/install.go
This pull request adds support for mssql (Microsoft SQL Server) databases. 
It depends on a pull request to xorm (go-xorm/xorm#469), which is mandatory to get mssql support for gogs without fundamental changes.
=> Adding mssql support.

models/repo.go
This won't fix any bugs, but a typo is a typo.
=> Fix typo in LocalCopyPath's path string

models/repo_collaboration.go, routers/api/v1/api.go, routers/api/v1/repo/collaborators.go
Implements List/Check/Delete-endpoints for Repo-Collaborators
Depends on gogits/go-gogs-client#51
```
GET /repos/:owner/:repo/collaborators
```
```
$ curl https://try.gogs.io/api/v1/repos/unknwon/gogs/collaborators
```
```
Status: 200 OK
Content-Type: application/json
```
``` json
[
{
"id": 1,
"username": "unknwon",
"full_name": "",
"email": "u@gogs.io",
"avatar_url": "/avatar_url/1",
"permissions": {
"admin": true,
"push": true,
"pull": true
}
}
]
```
```
GET /repos/:owner/:repo/collaborators/:collaborator
```
```
$ curl https://try.gogs.io/api/v1/repos/unknwon/gogs/collaborators/bkcsoft
```
```
Status: 204 No Content
```
```
Status: 404 Not Found
```
```
DELETE /repos/:owner/:repo/collaborators/:collaborator
```
```
$ curl -X DELETE …
```
=> Implement list/check/delete-endpoints collaborator

.pkgr.yml, packager/Procfile, vendor/vendor.json
This pull request fixes the packaging for https://packager.io/gh/pkgr/gogs, which started to fail about 2 weeks ago. It switches to the newest version of the go buildpack and adjusts some configuration related to the packaging.
I also ran into an issue while running govendor, with the commit 8be5635c28f40a85ce8e8f65c6118b4ee4e548e9 not longer existing in the macaron repo, hence the change. Let me know if you think I'm doing something wrong here.
The package properly builds on my branch at https://packager.io/gh/pkgr/gogs/build_runs/604
=> Fix packaging

Dockerfile.rpi
Helps with #4180, by making sure we can actually build the Docker image on the Pi.
Crazy shenanigans might happen soon™, in regards to the other portion of #4180.
Or I might volunteer to just upload images I build on my Pi.
=> Updated Dockerfile for Raspberry Pi, based on the normal Dockerfile

cmd/hook.go
Fixed typo whitin commit https://github.com/gogits/gogs/commit/83f6b8e8474248bdad48aef5173695734d5fe5bc
=> fixed typo within cmd/hook.go

conf/app.ini
This PR fixes the follow issues:
1. wrong language name: "Suomalainen" is incorrect name for Finnish language, should be "suomi".
2. wrong capitalization of language names: different languages have different conventions for capitalization.
=> Fix language names

cmd/web.go, routers/user/setting.go, templates/user/settings/navbar.tmpl, templates/user/settings/repos.tmpl
This is my first attempt at adding a personal repositories panel under "User Settings" (Issue #4277).  
One of the things that needs to be reviewed is my use of the ```[admin]``` localization variables since these do not exist under ```[settings]``` yet.  I'm not sure what the process is for adding to the localization files or if you even want to bother with that for this PR or not.  
Currently, it will only display repositories that the logged in user owns and will only allow the logged in user to delete his own repositories.
=> Repositories panel in personal settings

models/repo.go
The list returned by SearchRepositoryByName has duplicate entries and, as consequence, `/explore/repos` list replicated entries too:
``` sql
SELECT  * FROM "repository" AS "repo" LEFT JOIN "access" ON access.repo_id = repo.id WHERE (repo.owner_id = 1 OR access.user_id = 1 OR repo.is_private = true) ORDER BY repo.updated_unix DESC LIMIT 10;
```
For example:
```
id  | owner_id |         lower_name          |            name             |                 description                 | website | default_branch | num_watches | num_stars | num_forks | num_issues | num_closed_issues | num_pulls | num_closed_pulls | num_milestones | num_closed_milestones | is_private | is_bare | is_mirror | enable_wiki | enable_external_wiki | external_wiki_url | enable_issues | enable_external_tracker | …
```
=> Avoid duplicated results in SearchRepositoryByName

models/mirror.go
Mirror.NextUpdate is not properly set because the switch-case has the wrong column name. Changed from next_update**d**_unix to next_update_unix.
=> Corrected Mirror.NextUpdate not set

docker/README.md
The unicode non-breaking space character was breaking the heading format; this switches that character for an ASCII space.
=> Fix heading in README.md

public/js/gogs.js
$('#id test') is a shortcut for $('#id').find('test')
By using find(), we are eliminating some function calls. which is always good ;)
=> Small JS improvement: Use jQuery .find()

models/migrations/v17.go
This patch adds error handling for mysql in addition to the existing sqlite error check. Without the additional error check, I'm seeing the following error:
`Fail to initialize ORM engine: migrate: do migrate: Error 1146: Table 'gogs.protect_branch_whitelist' doesn't exist`
=> Handle mysql error in migration

conf/locale/locale_en-US.ini
This adds a missing word in the description of the webhooks settings page and fixes a typo.
=> added missing word and fixed a typo

models/ssh_key.go
This pull request somewhat fixes #4507 by moving the the config variable check to a point before the loading of the key is done. That way we avoid the problem of ssh-keygen returning weird stuff and returning an error.
The second commit is a small cleanup of two comments, where the x/crypto/ssh library did not support ed25519 keys, which it does now. The comments were removed and the proper constant was put into place.
=> don't run ssh-keygen check if disabled

models/login_source.go
This is a fix to #2855. 
The first time a user logs in with LDAP the database saves if they have the admin flag or not. Because of this if the LDAP source changes the user will still have the flag set for admin. This fix does a check to see if the user already exists in the database. If they exist then update, else create.
I think it could be probably improved with some way of checking that the user being updated has the same login source.
=> Add check for user for create/update on LDAP

models/org_team.go
Ensure that the IN clause contains one value at least. The idea is avoid a syntax error in the SQL sentence and rollbacks in the transactions.
For example:
```
ERROR:  syntax error at or near ")"
LINE 1: ...RE ... and team.id IN ();
```
We will always add the -1 value in the IN list so the IN clause always contains one element at least (`IN (-1)`. As `-1` is not a valid team `IN (-1)` acts like as a empty set.
=> getUserTeams uses includes always -1 in the IN statement to avoid SQL bad syntax errors

conf/app.ini
A 5 seconds default timeout is too low and can cause random timeouts in certain setups.
15 seconds is a nice default timeout, it's not too long, but it has a much lower chance of triggering the timeout.
=> Made the webhook timeout duration longer.

routers/repo/download.go
Allocated buffer served to client and not properly truncated to number of bytes read.
Fix for #4433
=> Fix for downloading zero bytes files.

templates/repo/commits_table.tmpl
This is a basic pull request to fix #4439; the `has-emoji` class seems to need to be on the html element that contains the emoji. In this case the html element that has the emoji is a child of the element with the `has-emoji` class, it was being ignored.
What I have done here is move the `has-emoji` class from the parent `<tr>`, attaching it to the child `<span>` element that contains the commit message with the potential of having emoji.
Before:
After:
=> Fixes #4439

cmd/admin.go
Just an English typo in the command line help.
=> Preform → Perform

conf/app.ini, pkg/setting/setting.go
An update to the attachment enable/disable toggle to match language used with other config sections (e.g. `[repository.upload]`, `[release.attachment]` or `[mailer]`) - namely:
```
[attachment]
ENABLE = false
```
Becomes...
```
[attachment]
ENABLED = false
```
Understand this might be a backward breaking change for some - and documentation/wiki would require updates too. Happy to assist where possible.
Peter
=> Rename app.ini attachment toggle from ENABLE to ENABLED

scripts/init/centos/gogs, scripts/init/debian/gogs, scripts/init/suse/gogs
If using postgresql or mysql for the gogs database then gogs doesn't start and the logs claim "database connection refused".
This PR adds mysql and postgresql as optional dependencies to the LSB init scripts so gogs will always start after mysql/postgresql _if_ they are present on the system. Thus allowing the initial database connection to succeed.
I've been using this updated init script for a few days on 2 independent Debian 8 servers both with gogs/mysql. No issues yet. I no longer need to ssh into the servers to manually start gogs after a restart. I've done at least a dozen restarts in the name of testing.
Don't forget to run `insserv gogs` after overwriting the old script with the new one to update the dependencies.
=> Added mysql and postgresql as optional dependencies in LSB init scripts.

public/css/gogs.css
Marking text in a diff will include the line numbers, resulting in copy pastes like this:
```
43	37	
/**
44		
-     * @return array
38	
+     * @inheritDoc
45	39	
*/
```
This pull request will tell browser to not include the line numbers when selecting text. Copy paste will then behave like the standard code-view. This is not a problem in code-view, since the structure of the table rendering the code is a bit different. 
This css property is [widely supported](http://caniuse.com/#feat=user-select-none). IE9 and lower is the only (most used) browsers not supporting it.
I could not find a relevant issue.
=> Do not include line numbers in diff selection

models/comment.go
This PR populates the `comment.Issue.Repo` struct using `getRepositoryByID()`. This is required to use the `ListIssueComments` API.
Fixes #4587.
=> Fix ListIssueComments API (#4587)

models/user.go
fix #4692 and corrected typo in [this comment](https://github.com/gogits/gogs/blob/develop/models/user.go#L495)<br />
changed this
> NewGhostUser creates and returns a fake user for someone has deleted his/her account.
into this:
> NewGhostUser creates and returns a fake user for someone who has deleted his/her account.
and added "explore" and "create" to the reserved user name list #4692
=> fix #4692 and typo in comments

cmd/admin.go
This PR adds CLI subcommands for all operations available in the web admin panel.
The `gogs admin` command now looks like this:
```
NAME:
Gogs admin - Allow using internal logic of Gogs without hacking into the source code
to make automatic initialization process more smoothly
USAGE:
Gogs admin command [command options] [arguments...]
COMMANDS:
create-user                  Create a new user in database
delete-inactive-users        Delete all inactive accounts
delete-repository-archives   Delete all repositories archives
delete-missing-repositories  Delete all repository records that lost Git files
collect-garbage              Do garbage collection on repositories
rewrite-public-keys          Rewrite '.ssh/authorized_keys' file (caution: non-Gogs keys will be lost)
resync-hooks …
```
=> Add CLI subcommands for all admin dashboard actions

Dockerfile, Dockerfile.aarch64, Dockerfile.rpi, Dockerfile.rpihub, docker/build.sh, docker/finalize.sh, docker/start.sh
Fix #3520 by allowing the UID and GID of the `git` user to be changed by passing the environment variables `PUID` and `GUID` in as part of the docker run command.
This is done using `usermod` and `groupmod` (included in the `shadow` package in the alpine testing repo). 
Prior to this pull request, gogs files are written using uid/gid 1000:1000 as these are the id's of the docker `git` user. Which in most cases, may not map to a meaningful user on the host. 
```
sudo docker create \
--name=gogs \
-p 22:22 \
-p 3000:3000 \
-e PUID=$(id $USER -u) -e PGID=$(id $USER -g) \
-v /var/gogs:/data \
-t gogs/gogs
```
Apologies for changing so much of the finalize.sh script. I had to in order for the container to build correctly (beforehand it would build, but /app/gogs/docker was empty) so that I …
=> Allow setting UID and GID when running a docker container

routes/api/v1/admin/org.go, routes/api/v1/api.go, routes/api/v1/org/org.go
We're more than pleased with Gogs and want to automate completely a migration from GitLab to Gogs.
We need API to create organizations.
Although the same can be achieved with the above mentioned endpoint, 
I don't feel it's correct since it's an admin endpoint and requires you to specify the `username` that will be the owner of the repo.
Also there's a feature request at https://github.com/gogits/go-gogs-client/issues/77.
~~Once this is merged I'll expose Client API for `go-gogs-client`.~~ Exposed `go-gogs-client` in https://github.com/gogits/go-gogs-client/pull/84
I haven't invested time into better code coverage due to the fact that we need to ship this soon. I will add tests in a separate PR later if that's okay with you.
@Unknwon
=> Add API endpoint /api/v1/user/orgs

conf/app.ini
台湾 is in Simplified Chinese (zh_CN), and 臺灣 is the correct version for Traditional Chinese (zh_TW).
Both 臺灣 and 台灣 are commonly used in Taiwan. According to [1][2], 臺灣 should be used in official documents, so I choose this version.
[1] http://news.ltn.com.tw/news/focus/paper/451629
[2] https://zh.wikipedia.org/wiki/%E8%87%BA%E7%81%A3#.E3.80.8C-.7B.E8.87.BA.7D-.E3.80.8D.E8.88.87.E3.80.8C-.7B.E5.8F.B0.7D-.E3.80.8D
=> Fix the language name for zh_TW

docker/s6/gogs/setup
This pull request addresses an issue I found in the setup script that is run inside the docker container on startup. Due to how trivial it is there is no open issue for this.
What currently happens: On first run, the following symlinks are created:
* /app/gogs/log -> /data/gogs/log
* /app/gogs/data -> /data/gogs/data
* /home/git -> /data/git
On second run (upgrade/restart) the following links are created because the existing target links are followed:
* /data/gogs/log/log -> /data/gogs/log
* /data/gogs/data/data -> /data/gogs/data
* /data/git/git -> /data/git
These are circular links. This pull request uses the -n option (treat LINK_NAME as a normal file if it is a symbolic link to a directory) to prevent this from happening on container restart.
=> Docker symlink fixes

scripts/build_freebsd.sh, scripts/build_linux64.sh
Before: `outPath=./output_$outPlattform_$outArch`
Variable referenced is `outPlattform_`
The shell includes the subsequent underscore as part of the variable name.
Before: `outPath=./output_${outPlattform}_$outArch`
Variable referenced is `outPlattform`
=> Fix overextending of variable name

pkg/tool/tool.go
Inspired by go-gitea/gitea#2767:
> Use geometric pattern image as default gravatar. It is easier to distinguish different people.
>
> Before:
> ![](https://camo.githubusercontent.com/bce3a056b81f604d890a84f83dff16691b7c82df/68747470733a2f2f692e696d6775722e636f6d2f4b41363738354b2e706e67)
> After:
> ![](https://camo.githubusercontent.com/334d84d544c561e67fc1c1016e7495e320d6950a/68747470733a2f2f692e696d6775722e636f6d2f5a7455344372682e706e67)
=> Use identicon image as the default gravatar.

pkg/context/context.go
Fixes #4926 
go-get=1 response now contains `<!doctype html>` and godoc.org can parse meta tags correctly.
=> Add doctype to go-get=1 reponse. Fixes #4926 

routes/repo/commit.go
- The `commits_table.tmpl` pagination uses a `$.FileName` variable in
order to generate the next/previous URLs, but it seems like that
variable was no longer being populated in `renderCommits`.
=> Fix file commit history pagination

templates/user/auth/login.tmpl
As gogs can be linked with PAM it is recommended to disable autocomplete on the password input.
=> Disable password autocomplete

templates/user/dashboard/issues.tmpl
this pull request adds issue labels (as normally appear in the /repo/issues tab) to the /issues page.
it is not related to an open issue in the tracker, but it does standardize the appearance between the places where lists of issues are shown.
=> Issuelist labels

.pkgr.yml
Update pkgr specifications to enable builds on Debian 9 (Stretch) since the Debian 8 (Jessie) .deb files will not work out of the box on a clean Debian 9 install.
=> Update pkgr spec to build on Debian 9 (Stretch)

routes/repo/issue.go
Hi,
Addresses issue #4514 
Simple pull request that remove the ability for users to delete protected branches after a successful merge.
I have compiled and tested and it works as intended for me on Windows and Linux/amd64
=> Disallow web ui to delete protected branch

models/repo.go
Sets BaseRepo value for each resulting fork in GetForks().
Finds correct permissions for parent repository in APIFormat().
The output JSON is a little redundant, perhaps we should offer a
different view of the api.Repository without the Parent attribute?
Signed-off-by: Dennis Chen <barracks510@gmail.com>
=> api: fix nil pointer dereference on repo/forks

cmd/web.go, routes/repo/http.go
Hello, this is my first time contributing to Gogs! I am the author of [isomorphic-git](https://github.com/isomorphic-git/isomorphic-git) which is a JavaScript implementation of git that runs in the browser. This enables web-based IDEs that can clone and push directly with git! One downside is that unlike on the desktop, in browsers we have the same-origin policy. This means you cannot clone directly from Github/Bitbucket/etc but must go through a proxy.
I am working to change this by adding the necessary CORS headers so that git clients in the browser will be able to fetch directly. Since Gogs is open source (unlike Github) I was able to make the change. (I am also sending a pull request to Gitlab with a similar change.)
I expect lots of questions/pushback because CORS is often …
=> repo/http: add CORS headers to allow clone/push from browser agents

templates/base/head.tmpl
Attempt to make https://github.com/gogits/gogs/issues/4778 better. It localizes the message which appears for people who have JavaScript disabled and makes the dropdowns work with CSS (only for people who have JS disabled, using the `<noscript>` HTML tag)
=> Make dropdowns menus work when JavaScript is disabled

conf/app.ini
It's a fun feature but `ENABLE_FEDERATED_AVATAR` being true by default leads to confusion and huge slowdowns (see #2838, #980, #914) — it's unexpected that Gogs requires DNS configured (?) for avatars.  
Avatar lookup is a niche feature that I don't believe should be enabled by default given how prone it is to causing problems.
Changes `ENABLE_FEDERATED_AVATAR` in `conf/app.ini` to be `false`.
=> Default to disabling federated avatar lookup

pkg/markup/markdown.go, pkg/markup/markup.go, pkg/markup/markup_test.go
Fixing issue #4706 
Issue mentions are now allowed between square brackets.
=> Fix #4706: Issue mentions should also render with square brackets

routes/user/setting.go
Updating avatar email yields "Uploaded file is not a image." error on https://try.gogs.io/user/settings/avatar.
Taken from go-gitea/gitea#3793 and go-gitea/gitea#3988
=> Fix avatar email update error

Makefile
```
[alimy@rover gogs]$ pwd
/home/alimy/art/arg/src/github.com/gogs/gogs
[alimy@rover gogs]$ echo $GOPATH
/home/alimy/art/ago:/home/alimy/art/arg
[alimy@rover gogs]$ make
go install "-v" -ldflags '-X "github.com/gogs/gogs/pkg/setting.BuildTime=2018-06-04 06:17:19 UTC" -X "github.com/gogs/gogs/pkg/setting.BuildGitHash=c08aab90ec696b7fcc56b8da0a468e74d266b89e"' -tags '""'
cp '/home/alimy/art/ago:/home/alimy/art/arg/bin/gogs' .
cp: cannot stat '/home/alimy/art/ago:/home/alimy/art/arg/bin/gogs': No such file or directory
Makefile:36: recipe for target 'build' failed
make: *** [build] Error 1
```
in this scene GOPATH have two item (/home/alimy/art/ago and /home/alimy/art/arg) and gogs source is not in first GOPATH items, when excecute go install ... will install to path that contain the source …
=> fix make build failure when enviroment of GOPATH have multiple items

routes/repo/view.go
fix #5261
Now the same viewing behavior as the GitHub/GitLab
=> Added deletion of an empty line at the end of file (#5261)

pkg/context/api.go, routes/api/v1/repo/repo.go
When I access to repository search API, I get this response
```http
> curl -i -XGET 'http://localhost:3000/api/v1/repos/search?q=repo&limit=1&page=1'
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Link: <http://localhost:3000/api/v1/repos/search?page=2>; rel="next",<http://localhost:3000/api/v1/repos/search?page=21>; rel="last"
```
It tell me it have second page, I'm try, but it also return the same as first page data.
I found it is not accept `page` parameter in `repo.Search` function, and `SetLinkHeader` are not use `limit` parameter from request to calculate page link, so i fixed it.
I also found in `go-gogs-client` project's wiki exclude `page` parameter in [repository search API](https://github.com/gogs/go-gogs-client/wiki/Repositories#search-repositories). Need to add …
=> Correct pagination in repository search API

models/repo.go
This pull request addresses issue #4973 
essentially if a repo is set to private and either (or both) the wiki or issue tracker are set to allow public access, they cannot be accessed without knowing the URL. The repo doesn't show in search or explore.
With these changes if the repo is private and either issue tracker or wiki are set to public then the repo will show in search and explore, but only the public pages can be accessed.
I'd suggest that maybe this behaviour should be enabled through a config option (per repo or for whole installation) but i'm not sufficiently capable with go to be able to implement that.
=> make repo show if any part is public

routes/repo/setting.go
https://github.com/gogs/gogs/blob/dfd494c113cfa2a25ee0c2f5a12c6403f24742a4/public/js/gogs.js#L1267 requires autosize to execute, which executes for "repo/settings/options". without this change, you get a JS error.
Technically, autoresize is only required for code with `SETTINGS_OPTIONS` rendering, but I found it kinda messy handling each case, so I guess browsers will take a minor JS loading hit. Let me know if this is good enough.
fixes #5314
=> require autosize when repo/settings/options is rendered

scripts/systemd/gogs.service
Disallow modifications to the system, disallow access to devices and separate temporary directory.
ProtectSystem=full # Make /boot, /etc and /usr read-only
PrivateDevices=yes # Disallow access to devices
PrivateTmp=yes # Make separate /tmp directory for gogs.
=> Apply hardening for systemd unit

docker/s6/gogs/setup
As per comments in issue, the recursive 'chown' command being removed in this patch causes problems with templates when run as a container, as well as delays service startup unnecessarily for users with large/slow repos.
=> Don't try to chown the git repos on startup (refs #4996).

templates/user/dashboard/dashboard.tmpl
The admin -> DISABLE_REGULAR_ORG_CREATION setting hides organization creation in the header, but not in the dashboard. The current button gives a 404 page.
This PR simply hides the button, using the same conditional found in the header template.
=> Hide dashboard org creation when not allowed

models/login_source.go, pkg/form/auth.go, routes/admin/auths.go, routes/user/auth.go, templates/admin/auth/edit.tmpl, templates/admin/auth/list.tmpl, templates/admin/auth/new.tmpl, templates/user/auth/login.tmpl
The changes will add a default authentication switch so that user doesn't need select their authentication source every time on the login page. This will save engineers time and money.
For example, if this select action from dropdown list will cost 1s and Gogs has 1,000,000 users, it will then cost 11.6 days on switching different authentication method. If one second will cost developer 1 cent, it will then save $10,000 money!
=> Add default Authentication Switch

pkg/auth/ldap/ldap.go
Fix for the case where group members are listed by member 'dn' - Issue (#4684)
Also, fixed typo in group member list return size check.
=> Fixes to group membership search handling

Dockerfile.aarch64hub
The shadow package contains the `usermod(8)` utility which is used by `start.sh` and `finalize.sh` to configure the git user.
The other Dockerfiles **do** install this package, for some reason it appears to have been missed in the aarch64hub variant. Further, I'm not sure that Dockerfile.aarch64hub is being used, but while trying to use it for building an aarch64 image I discovered issues with ssh login and the git user having the wrong uid/gid. Ultimately was able to debug this down to missing the usermod/groupmod utilities -- simple fix.
=> Dockerfile.aarch64hub: install shadow package

routes/repo/http.go
At some point after #4970 was merged, isomorphic-git started sending a custom User-Agent in its HTTP requests to deal with some services (\*cough\* gists \*cough\*) which filtered git traffic by User-Agent. Sadly, this broke cloning from Gogs using isomorphic-git in the browser (https://github.com/isomorphic-git/isomorphic-git/issues/555). This PR fixes it by telling browsers it is OK for CORS requests to send a custom User-Agent header.
=> repo/http: update CORS headers to allow custom user-agent

public/css/gogs.css, public/less/_dashboard.less
Fixes issue #5502. I used `overflow-wrap: break-word` rather than `word-break: break-all` because it will break long words without breaking regular sentences.
=> Fix issue 5502

routes/repo/issue.go
Resolves #5302.
Just added some code to the `GET /:user/:repo/issues/new` route to add `title` and `content` query string parameters to the context, so that they are prefilled in the from template when provided. The feature request mentioned using `body`, but `content` was already used in the template file so I went with that.
One thing to note is, with the current setup in [templates/repo/issue/comment_tab.tmpl](https://github.com/gogs/gogs/blob/master/templates/repo/issue/comment_tab.tmpl#L8), a repository's issue template takes precedence over the provided `content` query string parameter when templating the issue body, contrary to how it works on Github. @Unknwon Interested to see what your take on this is.
=> Implement issue title and content prefilling

templates/user/dashboard/dashboard.tmpl
The organisation dashboard page includes a _Mirror_ tab which has a _New Mirror_ (+) button. At the moment clicking this button goes to the _New Migration_ page with _This repository will be a mirror_ checked, but doesn't select the previously viewed organisation. This change makes it work like the _New Repository_ button from the same dashboard page which does select the previously viewed organisation.
=> Include org in new mirror url

pkg/markup/markup.go, pkg/markup/sanitizer.go
Allow to use !\[img](data:...) in markdown. (fix #5279)
=> Add data urls support for markdown images (fix #5279)

public/less/_repository.less
A fix for issue #5299.
Fixed by simple style modification.
I changed the width of `#clone-panel` to `auto`, but in Ubuntu, the length of `#repo-clone-url` is getting longer.
So I set `max-width` and `width` in `#clone-panel input`.
=> Fix layout misalignment in Firefox for Linux

conf/app.ini, pkg/mailer/mailer.go, pkg/setting/setting.go
This makes the sent messages less likely to be thrown away by spam filters, even if you DO want to be able to send HTML messages in general.
I know there's no opened issue or request for this, but I did it for myself and thought it would be nice to give you the chance to also add this very small feature that could potentially help people later on.
=> Support plaintext alt for HTML emails

README.md
I developed a simple Gogs launcher to allow our users to easily deploy Gogs on our cloud platform at https://github.com/LunaNode/launchgogs
It sets up Gogs via the Docker package and adds an HTTPS-enabled nginx reverse proxy. We're displaying the launcher internally but I noticed the Deploy to Cloud section and it'd be great if it can be added there as well!
=> README: add LunaNode cloud deployment URL

docker/sshd_config
This line has been removed in respect to the OpenSSH spec update with Version 7.5 (https://www.openssh.com/txt/release-7.5)
=> Change regarding Issue #5647

models/repo.go
This pull request as well as [this one](https://github.com/gogs/git-module/pull/40) is to address awkward English wording in an error message that I see on the System Notices Admin page of my Gogs installation. I hope to be able to help make this error message and perhaps others in the future read more naturally to native English speakers.
=> Idiomatic English

docker/s6/gogs/setup
The `chown` command in the setup file of Gogs is supposed to be executed just once. As soon as the app.ini file exists, this step should be skipped. However, the test was checking if a directory with the name app.ini exists instead of a file. Therefore, the `chown` command was executed on each boot.
=> docker: prevent Gogs from running a recursive chown on each boot

models/action.go, vendor/github.com/gogs/go-gogs-client/repo_hook.go
This goes along with https://github.com/gogs/go-gogs-client/issues/103 and https://github.com/gogs/go-gogs-client/pull/104
For Drone CI integrations, having the commit Sha in a create (tag) webhook event is being relied on for docker builds. See drone-plugins/drone-docker#229
This adds it to the payload.
Git tea does make this available, visible here https://github.com/go-gitea/go-sdk/blob/2858b80da5f75fa2eea3fcf3205a5e6fd16da0ec/gitea/hook.go#L196
=> Include the Sha in webhook create payloads.

pkg/context/context.go, pkg/context/notice.go, templates/base/head.tmpl
As discussed already on the forum (https://discuss.gogs.io/t/contributing-new-features-from-fork/2645), this PR adds a live notice banner to all GOGS pages when a notice file is found in the custom configuration directory.
In summary:
- Contexter checks if there is a file called `notice` under the `GOGS_CUSTOM` directory and loads it.
- The first line is treated as a header/title and everything else as the message body.
- Message body is rendered as HTML (tags allowed).
- File size is limited to 1024 bytes.
- File mime type must be text.
- Notice is rendered in `head.tmpl` for all pages.
I'm not sure whether it would be best for certain aspects of this to be configurable.  Perhaps the location and name of the file could be an optional setting (`$GOGS_CUSTOM/notice` by default), as well as …
=> pkg/context: Render live notice banner from file

.pkgr.yml, vendor/vendor.json
This PR fixes packager.io builds based on this repo, removes Debian 7 and Ubuntu 12.04 which are out of support, and adds Debian 10 and Ubuntu 18.04.
Builds are available at https://packager.io/gh/half-duplex/gogs/refs/develop - I don't have machines other than Debian 10 available to test, but I haven't had any problems there.
The existing deb repo, built from https://github.com/pkgr/gogs/tree/pkgr, is very out-of-date, see https://github.com/gogs/docs/pull/232. Is there any interest in just enabling packager.io for this repo directly? It's a couple clicks by a maintainer at https://packager.io/apps/new, and maybe changing branches to `master,develop` to offer pre-release builds.
Possible concerns:
- Are there any other officially supported heroku-related things that the vendor.json …
=> Fix and update packager.io build files

Dockerfile, Dockerfile.aarch64, Dockerfile.rpi, Dockerfile.rpihub
Add rsync to docker.
Rsync is nearly a necessity to optimize backup inside Openshift container.
Using TAR (default without Rsync), the process of external backup constantly stops at the middle.
=> Add rsync to dockerDevelop

docker/s6/gogs/setup
When gogs on docker starts for the first time, change owner of /data, /app/gogs and ~git/ to git.
The current checking way is whether /data/gogs/conf/app.ini exists or not. (refer to https://github.com/gogs/gogs/pull/5724)
But if I already prepared app.ini file before and override /data/gogs/conf/app.ini, changing owner logic is skipped.
For example, I use docker-compose.yml as the following.
```
version: '3'
services:
gogs:
depends_on:
- mysql
image: gogs/gogs
hostname: gogs
networks:
- default
ports:
- "3000:3000"
- "10022:22"
volumes:
- git-data:/data/
- ./gogs/conf/app.ini:/data/gogs/conf/app.ini
```
So, I changed initial checking logic that owner of /data is 'git' as the following.
```
if [ $(stat -c '%U' /data) != 'git' ]; then
```
When owner of /data is not 'git', change owner of …
=> docker: change how to check whether initial or not

pkg/auth/ldap/ldap.go
Minor fix that reduces two lines incorrectly logged as Error to Trace level.
=> ldap: log two non-errors on Trace level

scripts/init/ddwrt/S801gogs
Init script for DDWRT / Entware.
Present init script examples are not suitable for embedded systems, however, arm is indeed supported by gogs.
This PR is targeting issue #5794.
=> ddwrt / entware init script

routes/api/v1/user/follower.go
It appears that the current behavior is to always return not found on a call to `checkUserFollowing`. This was introduced in f1e0ebfe937213be2af4a3180fae9f43949de00e, when `c.Status(204)` was incorrectly replaced with `c.NotFound()`. I have replaced this with `c.NoContent()`.
Found with [LGTM.com](https://lgtm.com/projects/g/gogs/gogs/alerts/?mode=list&lang=go), on which I am a developer.
=> api/v1: fix status response in checkUserFollowing

internal/cmd/web.go
* Enable X25519 curve and reorder curve list to improve key exchange performance
* Enable ECDSA ciphers for EC certs
* Enable CHACHA20_POLY1305 ciphers
* Disable RSA key exchange algorithm which don't provide PFS
* Disable non-AEAD ciphers
=> tls: update default CurvePreferences and CipherSuites

internal/route/repo/webhook.go
The contained closes #5882. This change removes a stale wiki link for Webhooks and replaces it with the valid wiki link.
=> fix stale webhook documenetation link

internal/route/user/setting.go
Check for email collisions when updating the entire user information, not when the username is being changed.
Changing a user's email address through `/user/settings` to an email address that's already taken shows an internal server error instead of the appropriate error message.
The `ErrEmailAlreadyUsed` error type was incorrectly checked for during the username update in the same function, when it is impossible for that error to occur.  This PR performs the check after the `db.UpdateUser()` call, which can return the "email already used" error, and renders the error message on the form accordingly, instead of failing with an internal server error.
Fixes #5899
=> user/setting: check for IsErrEmailAlreadyUsed when updating user

docker/s6/gogs/setup
I was going to open an issue for this, but thought it would be simpler to fix it directly.
When running gogs after the first time, if the image has changed (update rebuild), the `/app/gogs` directory will have changed owner back to root:root, but `/data` will likely not be since the data directories are likely to be persistent.
Checking `/app/gogs` separately fixes this.
This is only an issue if the contents of `/app/gogs` aren't world readable which, by default, they are.  But if the image is built on a machine where the permissions aren't as expected (e.g., different umask), the startup will fail while trying to read `templates/.VERSION`.
Still, in the general case, the permissions of `/app/gogs` are changed to `git:git` on first run and rebuilding the container from a new image reverts …
=> docker: check "/app/gogs" separately on startup

internal/context/repo.go, internal/route/repo/issue.go
fixes #5677 
Added `MakeURL` method to `Repository`
`MakeURL` gets `string` or `url.URL` as argument and returns URL prepended with repository URL
=> repo: fix redirect after opening/closing milestone

go.mod, go.sum, internal/route/api/v1/misc/markdown.go
We already have a separate `/markdown/raw` API, remove redundant functionality here.
=> api/misc/markdown: remove Mode option

internal/route/repo/pull.go
Hello.
I migrate from bitbacket to gogs, and in PR i want to be able auto fill PR title field.
So i write some simple code for this feature and my explanation how it works.
It works like `.gogs/PULL_REQUEST.md`
But fills `pull request title field`.
And have some feature, like `branch placeholders`
For example init repository:
1. Init repo with `PULL_REQUEST_TITLE.md`
```bash
$ ... git init etc...
$ echo 'Merge {{headBranch}} into {{baseBranch}}' > .gogs/PULL_REQUEST_TITLE.md
$ git add . && git commit -m "custom pr title for gogs" && git push origin master
```
2. Then create new branch for test compare web form
```bash
$ git checkout -b test-1
$ echo 'changes in readme' > README.md
$ git add && git commit -m "changes in readme" && git push origin test-1
```
3. Go to link …
=> repo: able fill pull request title by template from md file

go.mod, internal/route/api/v1/api.go, internal/route/api/v1/repo/tree.go
This PR adds the tree  api endpoint to gogs api:
`GET/repos/:owner/:repo/git/trees/:tree_sha`
This new api endpoint that is being added is in conformance to
the GitHub REST API v3 specification. Documentation can be found
here: developer.github.com/v3/git/trees/#get-a-tree
For a given user, repo and sha value, this api (currently) returns
a single tree using the SHA1 value for that tree.
- Recursive implementation is yet to be implemented.
- Creating a Tree using POST is yet to be implemented.
Example curl:
```
l curl -H "Authorization: token REDACTED" http://localhost:3000/api/v1/repos/root/testrepo/git/trees/c59441ded1549b149def0d4c54594d31a7f3718f -X GET  | jq .
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed …
```
=> api: support getting repository Git tree (#5934)

public/js/gogs.js
`$.post().success -> $.post().done`
The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callback methods are removed as of jQuery 3.0. Need to use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.
=> public: fix jquery3.x syntax error

internal/route/install.go
After first time running the application and went through the installation, the flag was always true until restarted.
=> git: explicitly disable debug in prod mode

internal/cmd/serv.go, internal/conf/log.go
- Allow remove primary logger at better location
- Use more appropriate log.Error to replace log.Fatal
=> cmd/serv: improve hookMode handling

templates/mail/auth/reset_passwd.tmpl
Reset password email template contained a copypaste caused typo: it was telling about email address verification instead of password reset. This PR fixes that typo.
=> templates: fix copypaste of email verification in reset_passwd

internal/route/api/v1/api.go
This PR groups the contents api endpoint with both `""` and `/*` as
valid URL patterns.
When `""` is the URL pattern, this means that no repo path has'nt been
provided, in which case the path would be the default repo path.
When  `"/*"` is the URL pattern, then this would return the contents at
the specified path if it's valid.
Github API v3 is conformant to this behavior and have verified it
locally.
=> api: group "/contents" with "" and "/*" #5985

CHANGELOG.md, internal/context/context.go
=> http: always set header `X-Content-Type-Options` to `nosniff`

internal/db/release.go, internal/route/api/v1/api.go, internal/route/api/v1/repo/repo.go
Fixes #6012
Added the releases endpoint at `/repos/:user/:repo/releases`
https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository
=> api: support get releases endpoint

internal/db/error.go, internal/db/org_team.go
This means that when using the API to create a new team, the output contains the existing team ID, not just the name.
While there may be the thought that this reveals sensitive information, it is never the case that a user can create or update a team without permission to view the teams in the first place.
One of the reasons for this change is without an existing API to get a list of Teams and their IDs using the API, it would be impossible for an administrator to add themselves to an Owners team (or introspect the Teams at all), as they never know the Teams ID. This is one way to get that functionality without another API call, though that would also be useful.
=> db: include the Team ID in the error message

docker/s6/gogs/run, docker/s6/gogs/setup, docker/start.sh
Fixes [#6067 ](https://github.com/gogs/gogs/issues/6067)
- Create /data/* directory with git user
=> docker: fix the bug of using root account to create `/data/*` directory

docker/s6/gogs/run, docker/s6/gogs/setup, docker/start.sh
Resubmit: 
Fixes [#6067 ](https://github.com/gogs/gogs/issues/6067) : Create /data/* directory with git user.
The old commit [#6068 ] has a BUG(comments in https://github.com/gogs/gogs/commit/f3b05961aae82fa3e19c47f03c78974cf793fda3) : [`exec gosu $USER mkdir -p $f`](https://github.com/gogs/gogs/pull/6068/commits/e38c130c2d4f63014522276768cd5fe8d95ea0f3#diff-bdc913edcb71ddadcdcb8860a18f4527R36) will interrupt the execution of subsequent commands.
> The  exec() family of functions replaces the current process image with a new process image. 
**Install** and **Add ssh key** passed the test in docker run & docker-compose.
=> docker: fix the bug of using root to create /data/ directory

docker/start.sh
Fixed: mkdir sub-dir in /data failed when no mount volume.
> comments: https://github.com/gogs/gogs/pull/6106#issuecomment-614035480
=> docker: fix mkdir subdir in /data failed when no mount volume

CHANGELOG.md, internal/conf/conf.go
Scope:
* If the configuration file has wrong time format then use a default time format.
=> conf: fallback time layout to RFC 3339 when misconfigured

.github/workflows/lsif.yml
Sourcegraph's original published LSIF indexing CI guidelines had an error where the default setting on GitHub workflows would be for forks of the indexed repository to also build and upload LSIF indexes to Sourcegraph.com. The docs have been updated accordingly, and this PR contains the fix.
=> lsif: don't upload indexes for forks

docker/Dockerfile.aarch64, docker/Dockerfile.rpi
Dockerfiles for arm do not work currently. They don't use the correct base image for golang.
The 1.14 tag is based on a debian image. The gogs Dockerfiles are written to work with alpine.
This pull request just updates the Dockerfiles to include the alpine tag for golang. I used alpine 3.11 as this is what the main Dockerfile uses.
Fixes #6182.
=> Update Dockerfiles for ARM to use alpine golang

.github/workflows/shell.yml, scripts/build.sh
This pull request adds Shellcheck as a github work flow to provide linting for shell scripts. In addition to adding the workflow I have made some small changes to one shell script to ensure that it successfully passed that file.
There are quite a number of recommendations being made by shell check, I can make those adjustments as well but I wanted to keep this commit small.
=> workflow: add shellcheck as a linter

docker/Dockerfile.rpi
Previous link to arm64 package was incorrect due to different architecture with Raspberry PI devices.
=> docker: fix gosu link in Dockerfile.rpi

internal/osutil/osutil.go, internal/osutil/osutil_test.go
Previously Gogs got the current user via environment variables.
As Golang supports this via the standard library, this function is
now used instead and environment variables are only used if it fails.
Fixes #6219
=> osutil: use system API to get the username when env vars are empty

internal/db/repo.go
Follow up of #6176, otherwise the existing rows will have NULL and makes the `is_unlisted = false` condition ineffective.
cc @achilleas-k
=> repo: set default value for `is_unlisted` column

internal/db/db.go
After changing the connection attribute, a new session is required for thread-safe sharing in GORM v2.
Fixes https://github.com/gogs/gogs/issues/6334
=> db: create new session for MySQL after changing attribute

internal/context/context.go
Fix the typo of `Access-Control-Allow-Credentials` header.
=> context: fix Access-Control-Allow-Credentials header typo

scripts/mysql.sql
`innodb_file_format` and `innodb_large_prefix` have been deprecated with MariaDB v10.2 and removed with v10.3.1. They have been reintroduced with v10.4.3 but remain deprecated and unused:
- https://mariadb.com/kb/en/innodb-system-variables/#innodb_file_format
- https://mariadb.com/kb/en/innodb-system-variables/#innodb_large_prefix
Setting those variables on MariaDB >=10.3.1 leads to the following error:
```
ERROR 1238 (HY000) at line 7: Variable 'innodb_file_format' is a read only variable
```
Since semantic versioning patch versions cannot be compared via numeric operators, only the major + minor versions are compared against 10.3. Since v10.2.2 the defaults match the desired values, so there is only the single patch version 10.3.0 where, when explicitly set differently via MariaDB …
=> scripts: fix MySQL script for MariaDB >= 10.3.1

CHANGELOG.md, internal/form/repo.go
This will fix the issue of #6413 
Related reference: https://github.com/go-gitea/gitea/pull/13525
=> repo: disallow urlencoded new lines in git protocol paths

README.md
Updated tutorial section adding peppe8o.com tutorial to install Gogs on a cheap Raspberry PI Zero W with MariaDB database.
=> README: add a new RPI Zero W tutorial

Dockerfile, docker/Dockerfile.aarch64, docker/Dockerfile.rpi
This is a Dockerfile refactor, which will help reduce the image size and image layers. So I don't think it will need an issue opened first, hopefully it's acceptable, please let me know, if it's not, before directly close this PR, I could open an issue for it if it's required! Thanks!
=> docker: reduce additional image layer for the not executable gosu binary

docker/README.md
As Described in #6572 Port 10080 has being blocked default by modern Browsers, i suggest changing the default port.
=> docker: update default port to be exposed on the host

Dockerfile, docker/Dockerfile.aarch64, docker/Dockerfile.rpi
This pull request provides the required updates to the 3 dockerfiles which enables support for dockers built-in healthchecks.
The healthcheck shows a containers status as healthy if both:
* SSH (TCP 22) can be connected to via a TCP Port open request
* The Web Portal (TCP 3000) home page returns a HTTP 200 code response
Fixes #5935
=> docker: add Healthcheck support

.gitignore, go.mod, go.sum
This fixes runtime panic on macOS with Go 1.17
=> dep: update golang.org/x/sys

internal/db/models.go
The healthcheck endpoint panics on pinging on a `*xorm.Engine` with `nil` value, and it doesn't make sense to ping in such cases.
Link to the issue: https://github.com/gogs/gogs/discussions/6672#discussioncomment-1845476
=> db: skip ping when not available

README.md
GitHub URLs are case sensitive. Update 'contributing.md' link to 'CONTRIBUTING.md' so that the link is no longer dead.
In the current state of the repository, if you click on the 'contributing guide' link in README.md, you get a 404 page.
- N/A I have added test cases to cover the new code.
=> chore: fix dead link in README

docs/dev/release/release_new_version.md
The `--amend` flag is not doing what we expect, we should instead always create a brand new manifest.
Link to the issue: https://github.com/gogs/gogs/issues/6737
=> docs: delete and re-create Docker manifest for release

Dockerfile
Checking against SSH port involves complex issue like setting up proper private keys, it does not feel worth the effort to keep it as long as we are still checking against the HTTP endpoint.
Link to the issue: https://github.com/gogs/gogs/issues/6727
=> docker: remove healthcheck against the SSH port

CHANGELOG.md, internal/auth/pam/pam.go
Disallow expired accounts or accounts with expired passwords to login.
Link to the issue: https://github.com/gogs/gogs/issues/6810
=> security: fix improper PAM authorization handling

docker/start.sh
Make sure docker start script only force file ownership on `/data` once.
We use NFS as a data drive and have lots of repositories, and our container times our (in k8s) before it is finish running `chown`.
This is a small change, without any practical implication except much faster container start.
See #6554
=> docker: check "/data" mount ownership before forcing it

internal/route/repo/webhook.go
"Webhooks Guide" URL is empty. "hooks_desc" has a %s which is not filled in code. With this patch it is.
=> webhook: add missing `%s` URL value for webhook description

.github/workflows/go.yml, .github/workflows/shell.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

internal/cmd/web.go
It is more useful to print the user-defined external URL than the server listening address.
=> web: print accessible URL on startup

internal/db/repo_editor.go, internal/db/repo_editor_test.go
I try to fix it, but it's not necessarily the best solution.
This commit is for informational purposes only. No test cases have been added yet.
=> repo_editor: prohibits uploading files to `.git.` directory 

CHANGELOG.md, internal/db/repo_editor.go
Link to the issue: fixes https://github.com/gogs/gogs/issues/6555
=> repo_editor: prohibit move files to to `.git` directory

CHANGELOG.md, internal/route/repo/http.go
The meaning of `NotFound` method has been changed since https://github.com/gogs/gogs/commit/07818d5fa5aef7dd7dca1d556f59c7a146a9b00c, which doesn't response anything to the client but a utility method from the router.
Link to the issue: fixes #6963
=> http: fix non-sense `NotFound` call

internal/db/pull.go
It does not make sense to proceed for either `UpdatePatch` or `PushToBaseRepo` if the head repository is missing. Previously was only checked for `UpdatePatch`, which would still cause panic for calls to `PushToBaseRepo`.
Link to the issue: https://github.com/gogs/gogs/issues/6963
=> pull: ignore PR status check if head repository is missing

CHANGELOG.md, internal/db/repo_editor.go, internal/db/repo_editor_test.go
Link to the issue: fixes https://github.com/gogs/gogs/issues/7000
=> repo_editor: check both styles of `os.PathSeparator` in all systems

internal/context/auth.go, internal/db/access_tokens.go, internal/db/access_tokens_test.go, internal/db/mocks.go, internal/route/lfs/route.go, internal/route/repo/http.go
Based on our actual usages, all we wanted from `Save` was to set the `updated_unix` column to be the unix seconds of the current time. It was a waste trying to update all columns for the row.
This PR repurposes the `Save` method to be `Touch` and only updates the `updated_unix` column as intended.
=> db: rename `AccessTokensStore.Save` to `Touch`

internal/cmd/serv.go, internal/context/repo.go, internal/db/access_tokens_test.go, internal/db/mock_gen.go, internal/db/mocks.go, internal/db/perms.go, internal/db/perms_test.go, internal/db/repo.go, internal/db/repo_branch.go, internal/db/ssh_key.go, internal/db/user.go, internal/route/api/v1/api.go, internal/route/lfs/route.go, internal/route/lfs/route_test.go, internal/route/repo/http.go
=> db: use `context` and go-mockgen for `PermsStore`

internal/cmd/web.go
enable etag header when serving static js&css file.  works well in my playground.
before:
after:
=> web: enable `ETag` to improve loading speed of static resources 

internal/db/lfs.go, internal/db/lfs_test.go, internal/db/mock_gen.go, internal/db/mocks.go, internal/route/lfs/basic.go, internal/route/lfs/basic_test.go, internal/route/lfs/batch.go, internal/route/lfs/batch_test.go
=> db: use `context` and go-mockgen for `LFSStore`

internal/context/auth.go, internal/context/go_get.go, internal/db/login_source_files_test.go, internal/db/login_sources_test.go, internal/db/mock_gen.go, internal/db/mocks.go, internal/db/user.go, internal/db/users.go, internal/db/users_test.go, internal/route/lfs/route.go, internal/route/lfs/route_test.go, internal/route/org/setting.go, internal/route/repo/http.go, internal/route/repo/tasks.go, internal/route/user/auth.go, internal/route/user/setting.go
=> db: use `context` and go-mockgen for `UsersStore`

internal/db/mock_gen.go, internal/db/mocks.go, internal/db/two_factors.go, internal/db/two_factors_test.go, internal/db/user.go, internal/route/lfs/route_test.go, internal/route/user/auth.go, internal/route/user/setting.go
=> db: use `context` and go-mockgen for `TwoFactorsStore`

internal/context/go_get.go, internal/db/db.go, internal/db/db_test.go, internal/db/mock_gen.go, internal/db/mocks.go, internal/db/repos.go, internal/db/repos_test.go, internal/route/api/v1/api.go, internal/route/lfs/route.go, internal/route/lfs/route_test.go, internal/route/repo/http.go, internal/route/repo/tasks.go
3. Specify the application name when connecting to Postgres
=> db: use `context` and go-mockgen for `ReposStore`

CHANGELOG.md, internal/db/webhook.go
Should only the hostname instead of the full URL for checking the webhook payload URL.
Link to the issue: fix https://github.com/gogs/gogs/issues/7074
=> webhook: validate against hostname instead of full URL

CHANGELOG.md, conf/app.ini, internal/netutil/netutil.go, internal/netutil/netutil_test.go
Allow using `*` as an escape hatch for all local network address.
Link to the issue: https://github.com/gogs/gogs/discussions/7048#discussioncomment-2930780
=> netutil: allow using `*` to match any hostname

scripts/systemd/gogs.service
解决Ubuntu22.04下mysqld.service为mysql.service时自启失败问题
Ubuntu22.04通过apt安装mysql时没有mysqld.service文件，只有mysql.service。
所以gogs.service会在mysql启动前启动，导致[...o/gogs/internal/route/install.go:75 GlobalInit()] Failed to initialize ORM engine: open database: dial tcp 127.0.0.1:3306: connect: connection refused
- [✅ ] I agree to follow the [Code of Conduct](https://go.dev/conduct) by submitting this pull request.
- [✅ ] I have read and acknowledge the [Contributing guide](https://github.com/gogs/gogs/blob/main/.github/CONTRIBUTING.md).
- [✅] I have added test cases to cover the new code.
=> systemd: add `mysql.service` to "After"

internal/cmd/backup.go, internal/db/ssh_key.go, internal/db/wiki.go, internal/lfsutil/storage_test.go, internal/route/lfs/basic.go, internal/ssh/ssh.go, internal/testutil/golden.go, templates/embed.go
The ioutil package has been deprecated as of Go v1.16: https://go.dev/doc/go1.16#ioutil This commit replaces ioutil functions with their respective io/os functions.
=> chore: remove usages of the deprecated `ioutil`

CHANGELOG.md, internal/db/repo_editor.go, internal/db/repo_editor_test.go
On case-insensitive file system, `.Git` is treated as `.git` so we need to be able to handle mixed cases.
Link to the issue: fixes https://github.com/gogs/gogs/issues/7030
=> fix(db): correctly check Git path on case-insensitive file system

CHANGELOG.md, internal/route/repo/commit.go
Set missing value on user variable, each time a new user is returned from db.
Fixes #7404
This commit fixes the email to user properly handing the returned data from database.
Currently every time we are returning a new user from database, we are caching the value.
But we are not setting value to variable `u`, resulting in missing link for user in commit log.
Second commit from same user on the list shown as expected.
Link to the issue: #7404
=> commit: fix `matchUsersWithCommitEmails`

internal/database/access_tokens.go, internal/database/access_tokens_test.go, internal/database/actions.go, internal/database/actions_test.go, internal/database/database.go, internal/database/lfs.go, internal/database/lfs_test.go, internal/database/login_sources.go, internal/database/login_sources_test.go, internal/database/mocks.go, internal/database/notices.go, internal/database/notices_test.go, internal/database/orgs.go, internal/database/orgs_test.go, internal/database/perms.go, internal/database/perms_test.go, internal/database/public_keys.go, internal/database/public_keys_test.go, internal/database/repos.go, internal/database/repos_test.go, internal/database/two_factors.go, internal/database/two_factors_test.go, internal/database/users.go, internal/database/users_test.go
=> internal/database: consistently use `Store` and `s` as receiver

.github/workflows/go.yml, gen.go
=> chore: upgrade go-mockgen for 1.22

internal/route/install.go
When the application is first launched and the app.ini is configured via the web page, the section name written to app.ini is 'mailer' (in install.go), but when app.ini is loaded, the section name read is 'email' (in conf.go). This causes the configured email server to fail to work.
- [y] I agree to follow the [Code of Conduct](https://go.dev/conduct) by submitting this pull request.
- [y] I have read and acknowledge the [Contributing guide](https://github.com/gogs/gogs/blob/main/.github/CONTRIBUTING.md).
- [n] I have added test cases to cover the new code or have provided the test plan.
I just changed app.ini section name, then it works.
#[mailer]
[email]
ENABLED = true
=> Fix issue: synchronize the section name[mailer/email] of app.ini

.editorconfig
…line changes on Windows
By default, Git automatically changes end_of_line between LF and CRLF.
In this case, when a file is opened in an editor with editorconfig on Windows, and then saved without any textual changes,
editorconfig will change end_of_line from CRLF to LF.
At the same time, Git will notice this change. You have to commit it or restore it.
Just let Git handle it, I suggest removing the setting of end_of_line in editorconfig.
Link to the issue:  n/a"
=> fix(.editorconfig): remove setting end_of_line and make Git track EOL changes on Windows

scripts/systemd/gogs.service
The value of RestartSec is suggested to be greater than 1. (defaults to 100 ms)
[suggestion on https://serverfault.com/](https://serverfault.com/questions/610795/is-it-better-to-use-the-systemd-service-units-restart-restartsec-or-use-a-sy).
The reason is that
"The default limit is to allow 5 restarts in a 10sec period. If a service goes over that threshold due to the Restart= config option in the service definition, it will not attempt to restart any further.
The rates are configured with the StartLimitIntervalSec= (defaults to 10 s) and StartLimitBurst= (defaults to 5) options and the Restart= option controls when SystemD tries to restart a service."
[explanation on https://serverfault.com/](https://serverfault.com/questions/845471/service-start-request-repeated-too-quickly-refusing-to-st …
=> fix(systemd script): define RestartSec as 2

internal/database/org.go
I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.
see issues https://github.com/alingse/go-linter-runner/issues/1
and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9241873083/job/25423942721
the repoIDs was only filled with `[0, 0, 0]` and this `In("repo_id",  repoIDs)` will not cause a real bug.
```
if len(repoIDs) > 0 {
if _, err = sess.Where("user_id = ?", user.ID).In("repo_id", repoIDs).Delete(new(Access)); err != nil {
return err
}
}
```
=> chore: fix miss makezero bug

templates/admin/dashboard.tmpl
When BuildTime is not populated, the information box in the Admin Dashboard looks a bit weird. 
Link to the issue: #7799 
1. Clone repo and get tools
2. Build the project using `go build -o gogs`
3. Run server, and check Admin Dashboard page
4. Build Information box should not overlap with the Build Commit field
=> Fix spacing if BuildTime is missing.

internal/route/install.go
fix SMTP password config name from PASSWD to PASSWORD on install.
After installation, I found that sending emails was not working. Then I noticed that the email password was not being loaded because the initial installation configured the password in a field called PASSWD but apparently this field was renamed to PASSWORD. I tested using the new name and the email was sent successfully.
=> install: fix SMTP password config name to save

Dockerfile
Related to #7864
Fix the path of the s6-svscan binary path in the Dockerfile. As mentionned in the issue, it is probably to the alpine base image change (from `3.17` to `3.21`).
Link to the issue: https://github.com/gogs/gogs/issues/7864#issuecomment-2558323928
Credit to @cryptovaltt
Build the image and check if the application can be ran. E.g.:
```bash
docker build -t gogs:working-7864 -f Dockerfile .
docker run --name=gogs -p 10022:22 -p 10880:3000 -v gogs:working-7864 --rm
```
=> Fix s6-svscan path in Dockerfile

internal/database/actions_test.go
Fixes tests data race found in https://github.com/gogs/gogs/actions/runs/12457230279/job/34771555537
=> database: lock mock properly to avoid data race in tests

internal/database/repo_editor.go, internal/route/repo/editor.go
Fixes https://github.com/gogs/gogs/security/advisories/GHSA-9pp6-wq8c-3w2c
Tested manually
=> repo: ignore unintended Git options for diff preview

CODEOWNERS, go.mod, go.sum, internal/database/release.go, internal/database/repo_editor.go
Fixes https://github.com/gogs/gogs/security/advisories/GHSA-m27m-h5gj-wwmg by including https://github.com/gogs/git-module/pull/110
Tested manually
=> dep: update github.com/gogs/git-module to v1.8.4

templates/repo/release/list.tmpl
a very simple change to the `templates/repo/release/list.tmpl` 
i changed this:
to this:
(yes)
=> Adding '|' to the releases page 

scripts/systemd/gogs.service
Remove syslog.target from service file, this target hasn't existed for over a decade.
https://github.com/systemd/systemd/blob/6aa8d43ade72e24c9426e604f7fc4b7582b9db7c/NEWS#L72-L73
=> gogs.service: Remove syslog.target
