gogs/gogs

conf/locale/locale_de-DE.ini, conf/locale/locale_en-US.ini
This PR contains some translation updates:
1) it adds missing translation into german (de_DE)
2) it improves two english texts a little bit
=> Translation update

routers/repo/repo.go
Note, this is now only fixed with Go version >= 1.4.2, see this bug in Go: https://github.com/golang/go/commit/07d86b1f2db73c6a0716aec4d4cd62dfacb04a21
=> Fix #807 parse the userinfo with the golang tools

models/publickey.go, routers/user/setting.go
It is now possible to input ssh keys in a number of formats: openssh, SSH2 or just the base64 encoded key.
=> Implement #798 Flexible ssh-key input

templates/home.tmpl
This is a Correction of the link to the docker stuff.
=> correction: updated docker link

conf/locale/locale_en-US.ini, models/publickey.go, routers/admin/admin.go, templates/admin/dashboard.tmpl
Rewrite all ssh keys again in .ssh/authorized_key. 
ps - sorry for extra change in language file, it was my emacs hook to remove space and empty lines in save.
refs #763
=> add a function to rewrite all public keys on admin request

public/ng/css/gogs.css, public/ng/less/gogs/settings.less, templates/user/settings/email.tmpl
Before: ![gogs go git service_old](https://cloud.githubusercontent.com/assets/557879/6016257/6316f9ec-ab90-11e4-9dac-02b4c298b61d.png)
After: ![gogs go git service](https://cloud.githubusercontent.com/assets/557879/6016258/631b9452-ab90-11e4-9d2d-fcbad6e2918e.png)
=> fix settings/email html&css

public/ng/js/gogs.js, public/ng/less/gogs/repository.less, scripts/start.bat, scripts/start.sh, templates/repo/diff.tmpl
=> fix lines highlighting at diff view

models/action.go
Code-wise: the fixing-part of the code now doesn't reference the issue any more, because this is done by the referencing-part of the code, which is called just before.
Fixes #462, #668, #732.
=> Referencing issues from commit messages is now possible.

public/ng/js/gogs.js
=> new lines highlighting format

public/ng/less/gogs/repository.less
=> fix highlighting css for del code

modules/base/markdown.go, public/ng/css/gogs.css
Adjust MentionPattern to not match users mid-sentence (or email addresses)
Fix link to user profile, update based on adjusted MentionPattern.
=> Fix user mention bug when parsing markdown documents

conf/locale/locale_de-DE.ini, conf/locale/locale_en-US.ini, conf/locale/locale_fr-CA.ini, conf/locale/locale_ja-JP.ini, conf/locale/locale_lv-LV.ini, conf/locale/locale_nl-NL.ini, conf/locale/locale_ru-RU.ini, conf/locale/locale_zh-CN.ini, conf/locale/locale_zh-HK.ini, modules/setting/setting.go, routers/home.go, templates/admin/config.tmpl, templates/home.tmpl
See #884 for the original request. I'd love some feedback for the tiny CR since it's my first.
=> Make Signup button display configurable - #884

models/token.go, routers/repo/http.go
Hi,
Here's my attempt to allow pushing by token. Not sure if there were any other places to change.
Let me know how it looks.
Thanks!
Edit - sent to gogs/master instead of gogs/dev by accident. Fixed now.
=> allow http push by token - #842

models/git_diff.go, routers/repo/commit.go, templates/repo/diff.tmpl
=> Link to previous commited source file (diff.view_file button) instead of returning 404 for deleted files.

modules/base/markdown.go
Fixes #921 and makes the Mention regexp be in line with the others
=> Fixes #921

models/migrations/migrations.go
The old migration had a few issues:
- It left old column names around
- It did not give the right access levels for owners and admins
Also, this includes a migration that fixes the authorization of owner teams, which was previously ORG_ADMIN (instead of ORG_OWNER)
=> Rewrite of access migration

public/ng/js/gogs.js, templates/repo/diff.tmpl
Sorry, my fault. Fix a little mistake in diff.tmpl
=> fix typo mistake in highlighting

modules/mailer/mailer.go
Fix: 504 5.5.2 <localhost>: Helo command rejected
=> Fix: 504 5.5.2 <localhost>: Helo command rejected

modules/auth/auth.go, routers/repo/http.go
This fixes the issue for #898 (and I've actually tested it and got it running production this time).
=> Attempt 3 to fix LDAP login issues when git pushing after password change

modules/git/commit.go, modules/git/submodule.go, routers/repo/view.go, templates/repo/view_list.tmpl
=> Handle submodules without a .gitmodules entry - fix #1023

public/ng/css/gogs.css, public/ng/less/gogs/dashboard.less
=> Fix the little default in the navbar of the dashboard

public/ng/css/gogs.css, public/ng/css/ui.css, public/ng/less/gogs/issue.less, public/ng/less/ui/form.less, public/ng/less/ui/menu.less, public/ng/less/ui/reset.less, public/ng/less/ui/var.less, routers/user/home.go, templates/user/issues.tmpl
Should fix templates inconsistency for the issues dashboard.
Related to  #650 and #707
=> Apply ng to issue dashboard

modules/base/markdown.go
Well that was easy. Again, this was for #637 and #738.
=> Exclude HTML tags from Markdown post-processing

routers/repo/repo.go
Allow to migrate through git:// protocol
=> Allow to migrate through git:// protocol

models/repo.go, modules/setting/setting.go
=> SSH config options

models/repo.go
Fixes #1207.
Fails my Travis build, but so does the develop branch which succeeds on the official Travis builds, so I'm interested in why my Travis builds from my repos fail but gogs' official repos are fine...
Should pass on your Travis server.
=> Fixes issue with LDAP inserting users with blank names.

public/ng/less/gogs/sign.less, templates/user/auth/signin.tmpl
Makes the text clickable to toggle the checkbox and more accessible, closes #1209.
=> Wrap remember me text and checkbox in a label

.travis.yml, conf/locale/locale_en-US.ini, models/login.go, modules/auth/auth_form.go, modules/auth/pam/pam.go, modules/auth/pam/pam_stub.go, public/ng/js/gogs.js, routers/admin/auths.go, templates/admin/auth/edit.tmpl, templates/admin/auth/new.tmpl
We've done this patch to add the PAM authentication and it seems to work for us. There are a couple of issues though:
1. we don't know how to make it conditional for just linux servers
2. the new label for some reason is not translated
=> Add PAM authentication

templates/install.tmpl
Admin Password field in install form must be of type password
=> install admin password field fix

modules/auth/admin.go, routers/admin/users.go, templates/admin/user/edit.tmpl
I fixed #1130 but need feedback.
Thanks! :+1:
=> Add full name field to admin's user edit page (fixes #1130)

models/git_diff.go, modules/base/template.go, modules/setting/setting.go, routers/repo/download.go, templates/repo/diff.tmpl, templates/repo/home.tmpl, templates/repo/view_file.tmpl
These are just the hrefs that my quick testing revealed to be most painful for my repos.
=> Allow space and/or percent in file and directory names

public/js/app.js, templates/repo/issue/create.tmpl
Issue https://github.com/gogits/gogs/issues/1422 autofocus implemented.
About the tab index not sure what is explained there. Github has not such a simple tabindex as described. In gogs maybe it can be enhanced but I would not prioritize it.
=> autofocus for new and edit issue forms

public/ng/js/lib/gogs-prism.js
* Range selection implemented
* URI update implemented
=> Syntax highlight

public/ng/js/lib/gogs-prism.js
* Scroll to first highlighted range (line) implemented.
* Line numbers even if the source language is not supported implemented.
=> scroll to first highlighted line

templates/repo/settings/navbar.tmpl
Really small fix - broken link. :)
=> Fix broken collaboration link in repo settings

public/ng/css/gogs.css, public/ng/less/gogs/repository.less, templates/repo/bare.tmpl
=> Remove SSH button when SSH it is disabled

conf/app.ini
fixed chinese character '语' to japanese KANJI '語' in language selection.
=> fixed chinese character to japanese KANJI

templates/install.tmpl
Check https://github.com/gogits/gogs/issues/1481
=> Correct form name to smtp_email to fix matching in InstallForm struct.

modules/auth/ldap/README.md
Noticed a couple of small issues with the Markdown in the LDAP README. This pull request fixes them.
=> Small style fixes to the LDAP module README

modules/mailer/mailer.go
=> Added supported of 'AUTH LOGIN'

.travis.yml
=> Add go 1.5 to .travis.yml

modules/base/tool.go
PR for #1608 
我这里没有Mac环境没法用codekit，还需要修改highlight.js的配置为
```javascript
hljs.configure({
classPrefix: 'language-'
})
```
=> Add allow attribute `class` to `<code>` tag

conf/app.ini, models/admin.go, modules/setting/setting.go, routers/admin/notice.go, templates/admin/notice.tmpl
=> New admin notice UI based on user list example

conf/app.ini, models/org.go, modules/setting/setting.go, routers/admin/notice.go, routers/admin/orgs.go, templates/admin/org/list.tmpl
=> Fix admin organization new ui

conf/app.ini, models/repo.go, modules/setting/setting.go, routers/admin/repos.go, templates/admin/repo/list.tmpl
=> Fix admin repos new ui

Dockerfile, docker/build.sh, docker/s6/gogs/run
- Removed unnecessary variables
- Fixed symbolic links creation
- Fixed enter point
- Less intermediate containers
=> Several bugfixes in Docker build

templates/repo/header.tmpl
a tiny feature I forgot to add. also fixed the mixed-indentation in the template file
=> Add links to forks/watchers/stars in new layout header

packager/debian/postinst
Fix #1669 in the develop branch
Restart the gogs service at the end of an update
=> Fix #1669 on develop

cmd/web.go, routers/api/v1/repo.go
I wanted to implement some more features like update repo, remove user and update user but that would cause some difficulties having to work on [go-gogs-client](https://github.com/gogits/go-gogs-client).
usage is as following:
DELETE /repos/:owner/:reponame
$ curl -X DELETE -H 'Authorization: token TOKEN_ID' https://try.gogs.io/api/v1/repos/soud/MyRepo
```
Status: 204 No Content
Content-Type: application/json
```
=> Added repository remove option to API

Dockerfile
=> Update gosu, this fixes #1756

docker/README.md
Now against develop. I will remove the previous PR.
=> fix typo in README for Docker

modules/auth/ldap/ldap.go
This fixes #1841 and a related bug with the UserDN by disallowing usernames with characters that could lead to LDAP injection attacks.
=> Sanitize input to LDAP authentication module

scripts/init/centos/gogs
=> adding extra check on logpath

docker/s6/gogs/setup, docker/s6/openssh/setup, docker/s6/syslogd/run, docker/start.sh
- Added `SOCAT_LINK` environment variable to prevent SOCAT link creation as dicussed in #1815 
- Added right & ownership directory rigths to `/data/git`, `/data/gogs` & `/data/ssh` preventing weird bug like #1893
- Added `syslogd` service
- gather `openssh` log
- print them to stdout to let us track it via `docker logs`
- Docker image for testing availlable at [orax/gogs](https://hub.docker.com/r/orax/gogs/tags/) tag `latest`
=> Docker Improvmement and small fix

templates/repo/issue/view_content.tmpl
=> Fix #1824 add tabindex

models/action.go, templates/user/dashboard/feeds.tmpl
=> Show issue title at dashboard

Dockerfile, docker/build.sh, docker/start.sh
- Alpine Package has been update changing the path to S6 binaries
- Updated path & added some debug to build.sh
=> Update S6 Path after Alpine Package update

public/less/_admin.less, templates/admin/dashboard.tmpl
=> Fix admin dashboard new ui

templates/admin/config.tmpl
=> Fix admin configuration new ui

Makefile, scripts/less.sh
Long story short - compile time improvement, automatic build of CSS & bindata reducing the risk of forgetting to recompile them. See the commits for details.
=> Makefile improvements

models/issue.go, modules/auth/ldap/ldap.go, modules/bindata/bindata.go
Few words found misspelled throughout the codebase by my strict IDE settings. There are should be no functional changes.
=> Fix misspelled words

models/wiki.go
=> Wiki pages containing question marks in their name weren't loading

templates/base/head.tmpl
Added a missing space, a missing "is" on the meta description tag and lowercased "Service".
=> Fix the description on head.tmpl

models/git_diff.go, models/git_diff_test.go, public/css/gogs.css, public/less/_repository.less, routers/repo/commit.go, templates/repo/diff_box.tmpl
cc @bkcsoft
Following up https://github.com/gogits/gogs/pull/2296
Not all lines are being highlighted, but not even GitHub or GitLab do it.
=> Highlight diff

templates/home.tmpl
Add a french translation to the home template.
=> Add fr-FR to home template

models/issue.go
Should correct #2375.
At least partially for the moment
=> Correction for issue #2375

modules/base/markdown.go, modules/base/tool.go
Implementing checklist-feature for the markdown-renderer (should work everywhere, not just for issues)
relates to #1048 :) (Though not as feature-complete as Github is, since github supports interactivly checking/unchecking without editing the issue)
=> [Feature] Markdown Checklist-rendering

routers/repo/repo.go
Fixes #2442 
@Unknwon should this be a setting in app.ini or should I leave it as is?
=> Admins are allowed to create repos for arbitrary Orgs

Dockerfile, Dockerfile.rpi, docker/build.sh, docker/nsswitch.conf
- Add nsswitch.conf to configure LibC Name Service inside the container (Resolve #2015)
- Change my email in the Dockerfile
- Update build script to install software as a `build-deps` virtual package so that adding a package to it will be automatically removed at the end of the build script
=> Update Dockerfile & build script and add /etc/nsswitch.conf

templates/home.tmpl
Is it okay now? :sweat_smile: :+1:
=> To add spanish translation to home template

models/git_diff.go, routers/repo/commit.go, routers/repo/pull.go, templates/repo/diff_box.tmpl
=> Refactoring of inline diff computing to prevent empty diff box.

public/css/gogs.css, public/less/_base.less, templates/repo/diff.tmpl
=> Split view fixed

modules/setting/setting.go
=> Fixed gravatar url

public/js/gogs.js, templates/repo/bare.tmpl, templates/repo/home.tmpl, templates/repo/wiki/view.tmpl
=> Remember last selected clone protocol

conf/locale/locale_en-US.ini
=> Change en-us localization "mirror from"  to "mirror of"

models/ssh_key.go
Same as #2534 but pull requesting into `develop`. Sorry!
=> Fixes #2447 (delete public key from authorized_keys)

routers/repo/issue.go, templates/repo/issue/view_content.tmpl
=> Implemented participant-listing for issue-pages (Fixes #2377)

routers/repo/http.go
=> Use pretty 404 pages in repo.HTTPBackend

models/branch.go, models/repo.go, models/repo_branch.go, routers/api/v1/api.go, routers/api/v1/convert/convert.go, routers/api/v1/repo/branch.go
Same as #2419 but on the develop branch.
=> Implement API for branches listing

docker/README.md
=> Add an important note about mapping the ssh port on the container to the host

public/less/_repository.less
=> Add avatar arrows to both pull request and issue forms

templates/repo/issue/new_form.tmpl
=> Fix tab index on new issue/comment form

routers/repo/release.go
Fixes #2596 using a fake user.
=> Fix for server error on release page when a user deleted their account

cmd/web.go, models/repo.go
This will solve 1059
Depends on gogits/go-gogs-client#20
=> Add default branch to repo payload

public/css/gogs.css, public/less/_base.less, public/less/_repository.less, templates/repo/header.tmpl
Dashboard, repo pages and organization have all have the been modified
See screenshot.
=> Change main content area bg to white, keep area above tabs grey

models/action.go, routers/user/home.go, routers/user/profile.go
=> Only show activities and repositories on the dashboard, that the user has access to

modules/mailer/mail.go
=> Fix issue email formatting. Addresses #2331

README.md
contributing link in README.md previously displays 404 error
=> Update contributing guidlines link

routers/repo/issue.go, routers/repo/pull.go, templates/repo/issue/comment_tab.tmpl
GitHub just announced [issue and pull request templates](https://github.com/blog/2111-issue-and-pull-request-templates).
This PR implements it in Gogs and also adds templates to be used on GitHub.
=> Implement issue and pull request templates

.github/CONTRIBUTING.md
=> Removed duplicate of paragraph

models/git_diff.go, templates/repo/diff_box.tmpl
Moving cache variable to template instead of in the struct.
=> Little refactoring of diff highlight.

.travis.yml
Add latest golang testing.
cc @Unknwon
=> test the latest version.

routers/repo/pull.go
The previous PR #2524 was not creating `refs/pull/<pr-id>/head` when a PR was freshly created but only after a explicit push to the corresponding head branch.
This PR adds this functionality (issue #1655).
=> Improved Pull Request refs

models/issue.go, templates/repo/issue/labels.tmpl, templates/repo/issue/list.tmpl
=> Add ForegroundColor for labels to resolve #2033

models/repo.go
=> Set DefaultBranch to master when importing a new repo.

public/js/gogs.js, templates/explore/repo_list.tmpl, templates/repo/commits_table.tmpl, templates/repo/home.tmpl, templates/repo/issue/list.tmpl, templates/repo/issue/view.tmpl, templates/repo/issue/view_title.tmpl, templates/repo/view_file.tmpl, templates/repo/view_list.tmpl, templates/user/dashboard/feeds.tmpl, templates/user/dashboard/issues.tmpl
Currently Gogs doesn't render emojis in much places. This patch fixes this. (I am sure I still missed some places, though).
- [image](https://cloud.githubusercontent.com/assets/7011819/13480467/d59dc2ea-e0bc-11e5-8594-fc1bbd42ac49.png)
- [image](https://cloud.githubusercontent.com/assets/7011819/13480496/f1162972-e0bc-11e5-99e1-21926231b129.png)
- [image](https://cloud.githubusercontent.com/assets/7011819/13480516/123599b2-e0bd-11e5-852b-75cda81ed2cd.png)
- [image](https://cloud.githubusercontent.com/assets/7011819/13480523/222bc468-e0bd-11e5-8a17-98915faf56d3.png)
- [image](https://cloud.githubusercontent.com/assets/7011819/13480529/2df6da6c-e0bd-11e5-82b5-a29c94a61e06.png)
=> Render emojis in more places.

routers/user/home.go
readds the dashboard keyword to the title on the dashboard pages
addresses #2632
=> readd 'dashboard' to title

modules/context/repo.go
Removes accidental debug statement
=> remove errant debug statement

templates/repo/commits_table.tmpl
=> Grey out merge commits

public/less/_base.less
By adding a Japanese font in the less file, easier to see the display in Japanese.
=> Add Japanese Fonts

conf/app.ini, modules/setting/setting.go
As suggested, here's the code for a custom AppDataPath. #2794
=> Making AppDataPath customizable.

conf/locale/locale_en-US.ini, routers/user/auth.go
This resolves #2811.
One question I have is should I update bindata.go or does this get updated 'automatically' when needed?
=> Prevent `Forgot Password` for non local users

templates/repo/issue/new_form.tmpl, templates/repo/pulls/compare.tmpl
Add proper escaping of '#' in branchname in compare when doing pull
requests. This addresses issue #2822.
=> Fix problems with '#' in branchname

modules/template/template.go
=> Fixes #2842 Parses URL through EscapePound template function

modules/bindata/bindata.go, public/css/gogs.css, public/less/_base.less, public/less/_repository.less
=> Fixed #2909

routers/repo/download.go
=> Set utf-8 charset header for text files when serving raw content

models/issue.go, routers/repo/issue.go
Another try to get fine for https://github.com/gogits/gogs/issues/2892, but I need confirmation again that this works like expected.
=> Made the issue stats query more secure with parameterized placeholders

models/org.go
=> Fix listing team members #3031

models/admin.go
As asked here: https://github.com/gogits/gogs/issues/1738#issuecomment-218917124
/cc @Unknwon
=> Add comment note

cmd/dump.go
=> Add output flag for  `gogs dump`

modules/mailer/mailer.go
=> Do not write HTML in text/plain mail part

models/repo.go
num_issues and num_closed_issues don't contain the PR-issues.
=> Fix negative issue count set by Check Repository Statistics

conf/locale/TRANSLATORS
As you included Czech translation to official distribution, I think I'm missing here.
I know, selfish as hell... ;)
=> Adding myself to translators

routers/repo/view.go
=> Include repository owner name and description in html title

scripts/init/openbsd/gogs
=> Add an OpenBSD daemon control script

routers/api/v1/convert/convert.go
Adds created_at and updated_at properties.  See #3140 
This change is dependent on gogits/go-gogs-client#34
=> Add timestamps to repository api response

public/less/_base.less
Adding japanese Font. already added this PR https://github.com/gogits/gogs/pull/2816.
but, it does not applied navbar and some object.
=> Add Japanese Font(more)

routers/api/v1/admin/user.go
Requires PR 36 from go-gogs-client, https://github.com/gogits/go-gogs-client/pull/36
=> Added Full Name to CreateUser api call

routers/repo/release.go
When calculating the current behind commit count the calculation should
use the current release target to get the total commit count.
This fixes #3326
=> routers/repo/release: Use correct branch reference

models/git_diff.go, routers/repo/commit.go
=> Diff patch

models/issue.go
=> Fix for #3401 - Links of pull request comment email should use pulls URL

conf/locale/locale_en-US.ini, modules/template/template.go, public/less/_repository.less, templates/repo/issue/view_content.tmpl
=> Do not show non-image attachment in a <img> tag. Fixes #3215

modules/context/repo.go, modules/template/template.go, public/css/gogs.css, public/less/_repository.less, routers/repo/commit.go, routers/repo/pull.go, routers/repo/view.go, templates/repo/diff_box.tmpl, templates/repo/view_file.tmpl
Closes #3182
---
In the future, after #3151 being merged, we can also make the editor use the specs in `.editorconfig`.
=> On showing diff/file, use the tab_width specified on .editorconfig, if any

routers/api/v1/repo/issue.go
Adds support to change an Issues status via the REST-API. (Fixes #3170)
Depends on gogits/go-gogs-client#41
(Edit: builds failing because of dependency)
=> Issues can be closed via API (#3170)

conf/app.ini
=> libravatar.org supports HTTPS

routers/api/v1/api.go, routers/api/v1/repo/issue_milestone.go, routers/api/v1/repo/milestone.go
Implements the ability to manage repository milestones and issue milestones via the API.
This PR depends on gogits/go-gogs-client#39
=> Additional API support for milestones

models/issue_comment.go, routers/api/v1/api.go, routers/api/v1/repo/issue_comment.go
Implements issue comments API as proposed in https://github.com/gogits/gogs/issues/1692#issuecomment-206590786
The API is similar to github API, except:
- ~~the list API still not supporting `since` parameters~~
- edit comment needs `index` query parameter
This PR depend on API client lib PR https://github.com/gogits/go-gogs-client/pull/26
docs
```
GET /repos/:owner/:repo/issues/:index/comments
```
Response
```
Status: 200 OK
Content-Type: application/json
```
```
[
{
"id": 4,
"type": 0,
"poster": {
"id": 1,
"username": "ibk",
"full_name": "",
"email": "ibk@xxx.net",
"avatar_url": "https://secure.gravatar.com/avatar/0d02f30bf8f58f6344ea19fd8e26ad6b"
},
"issue_id": 1,
"commit_id": 0,
"line": 0,
"content": "id 3 atau apa hayo?",
"created": "2016-04-09T11:06:35+07:00",
"created_unix": …
```
=> issues comment API : list, create, edit

.gopmfile, cmd/admin.go, cmd/cert_stub.go, cmd/cmd.go, cmd/dump.go, cmd/serve.go, cmd/update.go, cmd/web.go, glide.lock, glide.yaml, gogs.go
Codegangsta/cli has been renamed to urfave/cli
=> codegangsta/cli => urfave/cli

Makefile
These are to follow the GNU Coding Standards Makefile Targets:
https://www.gnu.org/prep/standards/html_node/Standard-Targets.html
=> Add all, check and dist Makefile rules

scripts/init/suse/gogs
Referring to #3557 here is a working init script for (open)SuSE distributions with Sys V init.
=> Add a (Open)SuSE init script

modules/markdown/markdown.go
Fix the RegExp to handle SHA of 40 characters and not less
=> Update size of SHA to fix #3538

templates/repo/editor/edit.tmpl
You can still see the wrong link error under preview .
=> fix error link under preview

modules/markdown/markdown.go
It a small fix for issue #3649.
=> Fix mention in comments like (@dblk)

models/pull.go, models/repo_mirror.go, models/update.go, models/webhook.go, routers/admin/auths.go
This PR fix string format verbs in log messages.
=> Fix string format verbs

modules/setting/setting.go
The pull request will be closed without any reasons if it does not satisfy any of following requirements:
1. Please make sure you are targeting the `develop` branch.
2. Please read contributing guidelines:
3. Please describe what your pull request does and which issue you're targeting
4. ... if it is not related to any particular issues, explain why we should not reject your pull request.
**You MUST delete above content including this line before posting; too lazy to take this action considered invalid pull request.**
Just to make it easier for administrator to configure libre avatar,
as it is done for "duoshuo" and "gravatar"
=> Add support for using "libravatar" as the GravatarSource

models/action.go, models/issue.go
=> Fix Typo Errors

models/ssh_key.go
https://github.com/gogits/gogs/issues/3480
Added regular exp match (108) and remove training new line (111) that cause system to think its an ssh2 key.
tested with Windows OpenSSH and OpenSSH2 keys
=> #3480 Fix new ssh key adding issues

conf/locale/TRANSLATORS, conf/locale/locale_de-DE.ini, conf/locale/locale_en-US.ini, conf/locale/locale_fr-FR.ini, conf/locale/locale_zh-CN.ini, routers/repo/editor.go
Prevents symlinks from being edited with the Web UI.
depends on https://github.com/gogits/git-module/pull/20
=> Check if file is a symlink with web editor

models/pull.go
Regarding https://github.com/gogits/gogs/issues/3484
Requires https://github.com/gogits/go-gogs-client/pull/47
=> PR Webhook - Add base/head info

conf/app.ini, modules/context/repo.go, modules/setting/setting.go, routers/repo/http.go, templates/repo/bare.tmpl, templates/repo/home.tmpl, templates/repo/wiki/view.tmpl
Relative to #2583, this Pull Request allow administrator to disable any Git interactions by HTTP protocol.
```
[repository]
DISABLE_HTTP_GIT = true
```
=> Feature #2583: Disable HTTP cloning

conf/locale/locale_gl-ES.ini
=> New locale "galician"

models/issue.go, routers/repo/issue.go, routers/user/home.go, templates/user/dashboard/issues.tmpl
This pull requests adds functionality to the Issues and Pull Requests view in the Dashboard. Previously these pages would only show Issues / Pull Requests placed in repositories **owned** by the user. This pull request changes the functionality of the "Assigned to you" and "Created by you" filters. These filters now show Issues / Pull Requests you are assigned to or you created from **any** repository. Issues related to this pull request are:
~~https://github.com/gogits/gogs/issues/3511~~
https://github.com/gogits/gogs/issues/1820
~~https://github.com/gogits/gogs/issues/2202~~
https://github.com/gogits/gogs/issues/1580
~~https://github.com/gogits/gogs/issues/2518~~
~~https://github.com/gogits/gogs/issues/2865~~
~~https://github.com/gogits/gogs/issues/3052~~ …
=> Fix assigned/created issues in dashboard.

README.md
This change makes the sentence in question clearer.
=> Rephrase sentence in README.md

routers/api/v1/api.go, routers/api/v1/repo/repo.go
Lists the forks of a repository at the /:user/:repo/forks endpoint.
Signed-off-by: Dennis Chen barracks510@gmail.com
=> api: display repository forks

models/user.go
Just a small patch for #3814.
Not sure if it's enough to cover all unwanted mailing situations.
=> Issue #3814 - Inactive users receive email notifications

conf/app.ini, modules/setting/setting.go, modules/ssh/ssh.go, routers/install.go
Update provides user with option to configure the cipher suite used for the built in SSH server
=> Configurable SSH cipher suite

cmd/web.go
This sets strong ciphers/curves for when TLS is used.
=> Use very strong ciphers

models/issue.go, routers/api/v1/api.go, routers/api/v1/repo/issue.go
This should implement the remaining Issue-endpoints. Had to refactor slightly so as to not duplicate code.
=> Implement the remaining issue-endpoints

modules/template/highlight/highlight.go
Enable syntax highlighting for CMakeLists.txt files #2199
=> Enable syntax highlighting for CMakeLists.txt files #2199

conf/locale/TRANSLATORS
Added myself to TRANSLATORS (galician language)
=> Added myself to TRANSLATORS

conf/locale/TRANSLATORS
The pull request will be closed without any reasons if it does not satisfy any of following requirements:
1. Please make sure you are targeting the `develop` branch.
2. Please read contributing guidelines:
3. Please describe what your pull request does and which issue you're targeting
4. ... if it is not related to any particular issues, explain why we should not reject your pull request.
**You MUST delete above content including this line before posting; too lazy to take this action considered invalid pull request.**
=> I've got Translation Credits message from 无闻 (joe2010xtmf)

routers/repo/wiki.go
Deal with '/' in Wiki page title.
=> this commit fix #3958

conf/locale/TRANSLATORS
Simply add me as translator (and fix the alphabetical sort).
=> Add me as translator

conf/app.ini, conf/locale/TRANSLATORS, templates/home.tmpl
- Add Ukrainian translation into templates/home.tmpl
- Fix Ukrainian language name in conf/app.ini
because on Ukrainian 'language' is female.
- Add me as translator into conf/locale/TRANSLATORS
=> Some translation changes relates to Ukrainian language.

models/org.go
This PR replaces the raw SQL queries for reading repositories of organizations. It resolves issue #4176.
Has been successfully tested with MSSQL Server.
=> Replaced raw SQL queries for reading repositories of organization

Dockerfile.aarch64
Include rpi changes in Dockerfile for aarch64
=> Update Dockerfile for aarch64

modules/context/context.go, routers/api/v1/api.go
Allow CORS requests for API, please check the thread at https://github.com/gogits/gogs/issues/3987#issuecomment-285258335
=> make CORS work by handling preflight OPTIONS request

cmd/web.go, conf/app.ini, pkg/setting/setting.go
Issue #4450 ([link](https://github.com/gogits/gogs/issues/4450))
Please let me know your thoughts, best regards
=> Allow configurable HTTPS SSL/TLS version (via app.ini)

models/repo.go
Hi,
This pull request modifies the behavior of the repository search to include searching within the repositories description. This is as per the issue #4287.
I have tested this in our production environment and no issues have been found.
=> Modified repository keyword search to include description for #4287

templates/repo/home.tmpl
fixed incorrect "clone" spelling
=> Fix typo in repo/home.tmpl

models/models.go
Just add utf8mb4 to connStr for mysql.
=> Add utf8mb4 to connStr for mysql. Visit (#4131)

models/models.go
Remove `,utf8` from `charset=utf8mb4,utf8`
=>  Update models.go. charset=utf8mb4 for mysql. 

templates/repo/branches/all.tmpl
Solve issue #4874 
I add EscapePound in name of branch.
=> Solve issue  #4874

templates/base/footer.tmpl
=> Update year in footer

templates/user/settings/email.tmpl
=> fix delete email button

models/repo_branch.go
Signed-off-by: Wendell Sun <iwendellsun@gmail.com>
Fixes #5053
=> Bug fix for query protected branches

public/assets/librejs/librejs.html, templates/base/head.tmpl
=> Update notebookjs to 0.3.0

conf/locale/TRANSLATORS
I received a message in Crowdin about adding translator credit.
Thanks.
=> locale: Add myself to TRANSLATORS

templates/user/dashboard/navbar.tmpl
in the activity/issues/PR info page move first divider to up layer make the page looks more concise
=> make page more concise for user's activity/issues/PR infomation

templates/mail/auth/activate.tmpl, templates/mail/auth/activate_email.tmpl, templates/mail/auth/register_notify.tmpl, templates/mail/auth/reset_passwd.tmpl
Its 2018 and the emails still say 2017
=> Update email copyright year

pkg/template/template.go, templates/repo/home.tmpl
For issue #4822 
- add new template filter function
- use it in repo home template
=> Simple html filter for repository description

templates/base/footer.tmpl, templates/base/head.tmpl, templates/home.tmpl, templates/mail/auth/activate.tmpl, templates/mail/auth/activate_email.tmpl, templates/mail/auth/register_notify.tmpl, templates/mail/auth/reset_passwd.tmpl, templates/org/home.tmpl, templates/repo/create.tmpl, templates/repo/header.tmpl, templates/repo/issue/labels.tmpl, templates/repo/issue/view_content.tmpl, templates/repo/release/new.tmpl, templates/repo/user_cards.tmpl, templates/user/profile.tmpl
Details at https://github.com/go-gitea/gitea/issues/315 and https://github.com/go-gitea/gitea/pull/4328.
Original credits to @denji .
I didn't touch any locales files as it seems to be only internal links, but I didn't digged in too much also because new locales are often added and there should be consistency...
=> [security] Add 'rel=noopener noreferrer' to <a> tags

routes/user/auth.go
=> Fix open redirect vulnerability #5364

scripts/systemd/gogs.service
Also add comment about unsupported options in different systemd versions.
=> Add NoNewPrivileges=true to systemd unit file

gogs.go
=> Remove app flags line

public/assets/librejs/librejs.html
currently incompatible with librejs
=> fix semantic version

Dockerfile.aarch64hub
old aarch64 dockerfile didn't work a long ago . this patch is fix this problem
fix aarch64 dockerfile make docker image error
=> fix aarch64 dockerfile make docker image error

docker/README.md
The pull request will be closed without any reasons if it does not satisfy any of following requirements:
1. Please make sure you are targeting the `develop` branch.
2. Please read contributing guidelines:
3. Please describe what your pull request does and which issue you're targeting
4. ... if it is not related to any particular issues, explain why we should not reject your pull request.
**You MUST delete above content including this line before posting; too lazy to take this action considered invalid pull request.**
=> Grammar fix

models/mirror.go
This PR is the continuation of the PR #5504. The reason I've opened another one is because I had branched from master and not develop, sorry for that.
This commit fixes issue #5473 and makes a new branch behave like a push event and trigger the appropriate webhook.
The solution here partially mimics the behaviour of Github when a new ref is created. Github adds to the payload of the `push` webhook the empty SHA "000000000..." for the previous commit and the latest commit for the new ref as the new commit, e.g.:
```
"before": "0000000000000000000000000000000000000000",
"after": "61164b65aa91cd4982e3ee8eaf108d3ebb265fd1",
```
The above was implemented in this PR. However Github also sends:
-  any commits that were made between the newest commit of the new ref and the last commit of its …
=> Fix #5473 Trigger push webhook on new branch

pkg/mailer/mail.go
=> Render markdown in emails

models/issue_mail.go
=> Add assignee to issue emails

README.md
Introduce a  deployment method which using helm charts on k8s.
=> introduce a  deployment method which using helm

README.md, README_ZH.md
The pull request will be closed without any reasons if it does not satisfy any of following requirements:
1. Please make sure you are targeting the `develop` branch.
2. Please read contributing guidelines:
3. Please describe what your pull request does and which issue you're targeting
4. ... if it is not related to any particular issues, explain why we should not reject your pull request.
**You MUST delete above content including this line before posting; too lazy to take this action considered invalid pull request.**
=> The link in README has been moved to a new place

scripts/mysql.sql
Fix to #5768 
I have tested it on MySQL 5.7, MySQL 8 and MariaDB 10.3
=> fixed mysql compatibility issue

templates/mail/auth/activate.tmpl, templates/mail/auth/activate_email.tmpl, templates/mail/auth/register_notify.tmpl, templates/mail/auth/reset_passwd.tmpl
=> templates/mail: modify the year at the footer

scripts/init/ddwrt/S801gogs
No particular issue called out here: general reliability improvements to support weaker routers.
- Removed reliance on sudo, daemonize deals with forking as user.
- Added wait for SQL as it may take more time to start up on a router: make sure you configure this before using.
- Proper Start/Stop/Reset is now implemented.
=> Improvements for ddwrt init script

conf/locale/locale_en-US.ini, models/error.go, models/errors/token.go, models/token.go, routes/api/v1/user/app.go, routes/user/setting.go
Fail with 422 Unprocessable Entity if the token name
already exist
ref: https://github.com/gogs/gogs/issues/5587
=> token: disallow multiple tokens with same name

routes/repo/download.go
ref: https://github.com/gogs/gogs/issues/5811
=> repo/download: add Last-Modified response header

internal/db/repo.go, internal/db/user.go
And protect local copy deletion with repoWorkingPool.
Solves https://github.com/gogs/gogs/issues/5823
=> repo: delete local copies on owner name change

go.mod, go.sum
=> go.mod: update github.com/gogs/go-libravatar

go.mod, go.sum, internal/db/org.go
=> Fix private repositories are hidden in the organization's view bug

internal/markup/markdown.go, internal/markup/markup.go, internal/route/api/v1/misc/markdown.go
Fixed a security issue reported by bluebird.
=> api: sanitize raw markdown content

internal/assets/templates/templates_gen.go, templates/repo/issue/comment_tab.tmpl
Reported in https://discuss.gogs.io/t/gogs/3062.
=> templates: fix not able to upload issue attachments

internal/context/api.go, internal/gitutil/error.go, internal/route/api/v1/api.go, internal/route/api/v1/repo/contents.go
This is what aligns with https://developer.github.com/v3/repos/contents/#get-contents.
cc @bharatnc since you're using this API, docs updated as well: https://github.com/gogs/docs-api/blob/master/Repositories/Contents.md#get-contents
=> api: overhaul `/repos/owner/repos/contents`

go.mod, go.sum
=> go.mod: update github.com/gogs/git-module

internal/cmd/web.go
=> csrf: set cookie HttpOnly and Secure

go.mod, go.sum
=> Revert "build(deps): bump xorm.io/builder from 0.3.6 to 0.3.7"

go.mod, go.sum
Follow up of gogs/git-module#57
cc @bharatnc
=> dep: bump github.com/gogs/git-module from 1.1.0 to 1.1.1

internal/cmd/web.go, internal/lfsutil/oid.go, internal/lfsutil/oid_test.go, internal/lfsutil/storage.go, internal/lfsutil/storage_test.go, internal/route/lfs/basic.go, internal/route/lfs/batch.go, internal/route/lfs/route.go
Able to actually push/pull LFS objects.
Fixes #1322
=> lfs: run e2e and fix minor issues

internal/app/api.go, internal/app/metrics.go, internal/cmd/web.go, internal/context/auth.go, internal/db/access.go, internal/route/home.go, internal/route/lfs/basic.go, internal/route/lfs/batch.go, internal/route/lfs/route.go, internal/route/repo/http.go
Not all routes need session, register session and CSRF middleware as global is a waste of resource, and creating a lot one-time off yet never used session records.
=> route: no session for routes without UI

internal/db/login_source.go
Since #6035, we use GORM to query single entry of `LoginSource` from database, and that caused the `core.Conversion` which is a feature of XORM to fail.
This is not the ultimate fix but good enough to help mitigate the immediate problem and will be worked properly during the DB code migration.
Fixes #6074
=> db: handle JSON conversion for `LoginSource`

.github/ISSUE_TEMPLATE/bug_report.md
=> github: update bug report template

CHANGELOG.md, internal/cmd/hook.go, internal/cmd/web.go, internal/route/lfs/route.go, internal/route/repo/pull.go, internal/route/repo/tasks.go
Fixes https://discuss.gogs.io/t/push-webhook/1189/
=> route: bypass require signin check for trigger repo tasks

docker/s6/gogs/run, docker/s6/gogs/setup, docker/start.sh
=> Revert "docker: fix the bug of using root account to create `/data/*` directory"

internal/db/db.go, internal/db/models.go
=> db: only use `AutoMigrate` to create new tables

internal/ssh/ssh.go
Fixes https://discuss.gogs.io/t/ssh/3106/14
=> ssh: ignore malformed "env" commands

internal/ssh/ssh.go
https://discuss.gogs.io/t/ssh/3106
=> ssh: improve env command processing

internal/route/api/v1/admin/org_team.go, internal/route/api/v1/api.go
=> api: add admin endpoint to get team members

CHANGELOG.md, go.sum, internal/cmd/admin.go, internal/cmd/backup.go, internal/cmd/restore.go, internal/cmd/serv.go, internal/cryptoutil/sha1.go, internal/cryptoutil/sha1_test.go, internal/db/access_tokens.go, internal/db/access_tokens_test.go, internal/db/backup.go, internal/db/backup_test.go, internal/db/db.go, internal/db/login_sources.go, internal/db/login_sources_test.go, internal/db/main_test.go, internal/db/models.go, internal/db/repos_test.go, internal/db/testdata/backup/AccessToken.golden.json, internal/db/testdata/backup/LFSObject.golden.json, internal/db/testdata/backup/LoginSource.golden.json, internal/db/two_factors_test.go, internal/db/users_test.go, internal/template/template.go, internal/testutil/golden.go, internal/tool/tool.go
=> db: use GORM to backup and restore non-legacy tables

README.md
=> README: remove OpenShift link

CHANGELOG.md, internal/context/context.go, internal/db/org_team.go
=> db: fix update team panic

CHANGELOG.md, internal/db/issue.go, internal/db/org.go, internal/route/org/members.go, internal/route/user/home.go
=> organization: limit showing at most 12 members in profile page

internal/osutil/osutil.go, internal/osutil/osutil_test.go
Follow up of https://github.com/gogs/gogs/pull/6246
=> osutil: update docstring and tests

internal/db/issue.go
Pull request with fix issue timestamp updating [#6209](https://github.com/gogs/gogs/issues/6209).
As you are using xorm events like BeforeUpdate () together with Cols (cols ...) method, it changes only fields wich you pass to Cols () method and BeforeUpdate () doesn’t work.
I think you also should check pull, release and repo updating. It may contains the same problem.
=> issue: fix timestamp updating

CHANGELOG.md, internal/db/login_sources.go
=> db: fix wrong column type of `login_source`

docker/runtime/backup-rotator.sh
=> docker: revert shellcheck fix

internal/route/install.go
Ref: https://github.com/gogs/gogs/issues/4765#issuecomment-683112712
=> install: fix generating removed options

Taskfile.yml, docs/dev/database_schema.md, docs/dev/import_locale.md, go.mod, go.sum, internal/db/backup.go, internal/db/backup_test.go, internal/db/db.go, internal/db/schemadoc/main.go
=> schemadoc: add go:generate to output database schema

CHANGELOG.md, internal/cmd/web.go, internal/context/context.go, internal/context/go_get.go
=> web: correctly serving go-get pages for subdirs

CHANGELOG.md, go.sum, internal/cmd/hook.go, internal/cmd/serv.go, internal/db/db.go, internal/db/models.go
=> cmd/serv: use different log files for ORMs in hook mode

CHANGELOG.md, docs/dev/release/issue_template_patch_release.md
Part of https://github.com/gogs/gogs/issues/6373
=> CHANGELOG: cut entries for 0.12.3

CHANGELOG.md, internal/context/context.go
Closes #6409 
I just added the X-Frame-Options header.
=> context: add X-Frame-Options header 

docker/runtime/backup-rotator.sh, internal/cmd/serv.go, internal/conf/computed.go, internal/conf/log.go, internal/context/repo.go, internal/db/issue_label.go, internal/db/mirror.go, internal/db/org.go, internal/db/pull.go, internal/db/release.go, internal/db/repo.go, internal/db/repo_branch.go, internal/db/ssh_key.go, internal/db/user.go, internal/db/user_mail.go, internal/db/webhook.go, internal/email/message.go, internal/httplib/httplib.go, internal/route/api/v1/user/key.go, internal/route/repo/release.go, internal/route/repo/setting.go, public/plugins/codemirror-5.17.0/mode/factor/factor.js, public/plugins/codemirror-5.17.0/mode/gas/gas.js, public/plugins/codemirror-5.17.0/mode/yaml/yaml.js, public/plugins/pdfjs-1.4.20/build/pdf.worker.js
This PR fixes/corrects multiple misspellings in comments (and a few in code).
Even though multiple files are modified, only 2-3 words are changed in each file.
=> chore: fix typos in code comments

templates/home.tmpl
added support for it-IT (italian language)
=> templates: add `it-IT` version of home page

internal/db/repo_tag.go, internal/route/api/v1/api.go, internal/route/api/v1/convert/convert.go, internal/route/api/v1/repo/tag.go
增加展示tag 列表的api 接口，期待您的批评指正
Add a rest api interface for displaying tag list, Looking forward to your reply。
=> api: support listing repository tags

Dockerfile
Modified  **Dockerfile** for adding the support for the development of docker image for ARM64 plarform
=> Dockerfile: add ARM64 and ARMhf support

internal/email/message.go
=> chore: fix typo in message.go

.github/workflows/docker.yml, Dockerfile, docker/Dockerfile.rpi
The `alpine3.14` includes some security fixes.
Link to the issue: https://github.com/gogs/gogs/issues/6674
=> docker: upgrade base images to `alpine3.14`

README.md
=> chore: fix dead links and wording in README

CHANGELOG.md
Link to the issue: https://github.com/gogs/gogs/issues/6731
=> CHANGELOG: cut entries for 0.12.4

README.md
Current build badge is workflow specific, which includes builds and failures from pull requests. Instead we should show the branch check status.
Link to the issue: "n/a"
=> README: use branch check status instead of workflow

.github/workflows/go.yml, go.mod, go.sum
=> ci: check Go module tidiness

docs/dev/release/release_new_version.md
=> docs: update release playbook for ARMv7

SECURITY.md
=> security: encourage reporting vulnerabilities through huntr.dev

README.md
Following discussion https://github.com/gogs/gogs/discussions/6774
Regards,
=> README: Add alwaysdata to Cloud providers

CHANGELOG.md, internal/form/repo.go, internal/netutil/netutil.go, internal/netutil/netutil_test.go, internal/route/repo/webhook.go, internal/route/repo/webhook_test.go
https://huntr.dev/bounties/327797d7-ae41-498f-9bff-cc0bf98cf531/ / [CVE-2022-0870](https://nvd.nist.gov/vuln/detail/CVE-2022-0870)
This pull requests contains a proposed patch for the vulnerability noted in the above links.
=> security: fix SSRF in repository migration

internal/db/repo_editor.go
Link to the issue: https://github.com/gogs/gogs/issues/6833
=> repo_editor: check upload `TreePath` and file name

.golangci.yml, internal/db/repos_test.go, internal/db/webhook_dingtalk.go, internal/db/webhook_discord.go, internal/db/webhook_slack.go
Link to the issue: fixes https://github.com/gogs/gogs/issues/6788
=> golangci-lint: add `unparam` linter

codecov.yml
It creates more noisy (making the build failing for patch diff) than usefulness. Having it comment on the PR is good enough.
=> codecov: disable GitHub Checks

.github/workflows/go.yml
Link to the issue: https://github.com/gogs/gogs/issues/6846
=> ci: delete Go 1.15 and add Go 1.18

CHANGELOG.md, docs/dev/local_development.md, go.mod, gogs.go
Link to the issue: https://github.com/gogs/gogs/issues/6846
=> go: update required version to be 1.16

CHANGELOG.md
Link to the issue: https://github.com/gogs/gogs/issues/6855
=> CHANGELOG: cut entries for 0.12.6

internal/cmd/restore.go, internal/db/backup.go
=> restore: clean up leftover and invalid chars

templates/repo/diff/box.tmpl
Follow up of https://github.com/gogs/gogs/commit/70c6f0a490e9d5dc03aa5f0dcb27c0a7879b1796
=> templates: use `OldIndex` for delete files in diff

go.mod, go.sum
Update the dependency in the hopes of fixing the issue.
Link to the issue: https://github.com/gogs/gogs/issues/6882
=> mod: update golang.org/x/crypto/ssh

conf/locale/TRANSLATORS
Added my name as translator as I helped with the French version (via Crowdin)
=> chore: update TRANSLATORS

internal/cmd/restore.go
Fix for https://github.com/gogs/gogs/issues/6913
=> restore: fix incorrect existence checking of "repositories.zip"

.github/pull_request_template.md
=> chore: fix dead link in pull request template

internal/cmd/web.go
Link to the issue: fixes https://github.com/gogs/gogs/issues/6919
=> attachment: set CSP header in the serving endpoint

Taskfile.yml, internal/context/context.go
Changes of "custom" directory requires restart/recompile and use lowercase header value to be consistent with others.
Link to the issue: "n/a"
=> chore: watch "custom" directory in dev and use lowercase for header value

CHANGELOG.md
Link to the issue: https://github.com/gogs/gogs/issues/6919
=> CHANGELOG: add entry for #6926

.github/ISSUE_TEMPLATE/dev_release_minor_version.md, .github/ISSUE_TEMPLATE/dev_release_patch_version.md
=> release: add step to publish GitHub security advisory

CHANGELOG.md
Link to the issue: https://github.com/gogs/gogs/issues/6930
=> CHANGELOG: cut entries for 0.12.7

internal/db/issue.go, internal/form/form.go
=> chore: fix lint errors

codecov.yml
=> codecov: make patch status to be informational

docs/dev/local_development.md
Link to the issue: fixes https://github.com/gogs/gogs/issues/6909
=> docs: use "go install" instead of "go get"

conf/locale/locale_ru-RU.ini
=> locale: sync from Crowdin

.github/workflows/docker.yml
Push ephemeral image to ttl.sh for pull requests, which doesn't require an account and automatically expires in 24 hours.
=> docker: push ephemeral image to ttl.sh for pull requests

CHANGELOG.md, conf/locale/locale_en-US.ini, internal/db/error.go, internal/db/webhook.go, internal/form/repo.go, internal/netutil/netutil.go, internal/netutil/netutil_test.go, internal/route/api/v1/repo/repo.go, internal/route/repo/repo.go, internal/route/repo/webhook.go, internal/route/repo/webhook_test.go
Link to the issue: fixes https://github.com/gogs/gogs/issues/6901
=> webhook: revalidate local hostname before each delivery

CHANGELOG.md
Part of https://github.com/gogs/gogs/issues/6991
=> CHANGELOG: cut entries for 0.12.8

.github/workflows/go.yml, .gitignore, go.mod, go.sum, internal/db/backup.go, internal/db/db.go, internal/db/db_test.go, internal/db/lfs_test.go, internal/db/login_sources_test.go, internal/db/main_test.go, internal/db/perms_test.go, internal/db/repos_test.go, internal/db/two_factors_test.go, internal/db/users_test.go
=> ci: run database tests against Postgres, MySQL and SQLite

.github/workflows/codeball.yml
=> ci: add Codeball

internal/db/access_tokens.go, internal/db/access_tokens_test.go
=> db: code tidy up for `AccessTokens`

.github/workflows/go.yml
=> ci: check tidiness of "task generate-schemadoc"

CHANGELOG.md, templates/repo/issue/list.tmpl
`DisplayName` allows all the characters from users, which leads to an XSS vulnerability when directly displayed in the issue list.
Link to the issue: https://github.com/gogs/security-issues/issues/1
=> issues: sanitize `DisplayName`

docs/dev/database_schema.md, internal/db/schemadoc/main.go
=> schemadoc: print table indexes

CHANGELOG.md
Link to the issue: https://github.com/gogs/gogs/issues/7023
=> CHANGELOG: cut entries for 0.12.9

.github/ISSUE_TEMPLATE/dev_release_minor_version.md, .github/ISSUE_TEMPLATE/dev_release_patch_version.md, docs/dev/release/release_new_version.md
=> release: minor updates to templates and docs

docker/README.md
=> docker: remove outdated info from README

internal/db/access_tokens.go
Turns out this tag is [still needed when deleting a user](https://github.com/gogs/gogs/blob/fe1d07f29caffe5604e604cae7e30bd7d24161f2/internal/db/user.go#L820).
=> db: add back xorm tag for `AccessToken.UserID`

internal/cmd/backup.go, internal/cmd/restore.go, internal/db/backup.go, internal/db/backup_test.go
Make all methods accept `context.Context`
=> db: use `context` for backup and restore

codecov.yml
=> chore: fix typo in codecov.yml

.pkgr.yml
=> pkgr: update supported distributions

internal/db/models.go
We don't care about warnings from ORMs.
Link to the issue: fix https://github.com/gogs/gogs/issues/7055
=> db: set XORM log level to error

internal/conf/testdata/TestInit.golden.ini
=> conf: update test golden file

conf/locale/TRANSLATORS
Added Simona Iacob as Translator for Romanian Language
=> chore: add Simona Iacob as translator for Romanian language

CHANGELOG.md
Link to the issue: https://github.com/gogs/gogs/issues/7118
=> CHANGELOG: cut entries for 0.12.10

.github/workflows/go.yml, CHANGELOG.md, go.mod, gogs.go, internal/db/actions.go, internal/db/repo.go, internal/httplib/httplib.go, internal/testutil/exec.go
=> go: update required version to be 1.17 and add 1.19 to CI

.golangci.yml, internal/context/repo.go, internal/db/user.go, internal/db/user_cache.go, internal/db/users.go, internal/db/users_test.go, internal/route/lfs/mocks_test.go, internal/route/repo/issue.go
=> refactor(db): move `User.HasForkedRepository` to `users.HasForkedRepository`

Taskfile.yml, internal/cmd/web.go, internal/conf/mocks.go, internal/conf/static.go, internal/db/issue_mail.go, internal/db/org.go, internal/db/repo.go, internal/db/user.go, internal/db/user_mail.go, internal/db/users.go, internal/db/users_test.go, internal/email/email.go, internal/route/admin/orgs.go, internal/route/admin/users.go, internal/route/api/v1/org/org.go, internal/route/api/v1/user/user.go, internal/route/home.go, internal/route/org/org.go, internal/route/repo/pull.go, internal/route/repo/repo.go, internal/route/repo/setting.go, internal/route/user/profile.go, internal/userutil/userutil.go, internal/userutil/userutil_test.go, templates/user/profile.tmpl
=> refactor(db): move some methods from `user.go` to `users.go`

internal/cmd/admin.go, internal/context/auth.go, internal/db/issue_mail.go, internal/db/user.go, internal/db/users.go, internal/route/admin/users.go, internal/route/api/v1/admin/user.go, internal/route/install.go, internal/route/user/auth.go, internal/route/user/setting.go
=> refactor(db): rename `User.Passwd` to `User.Password`

CHANGELOG.md, internal/context/auth.go, internal/db/access_tokens.go, internal/route/lfs/route.go, internal/route/lfs/route_test.go, internal/route/repo/http.go
As #6421 is not getting update, I created this PR to close #3866 . This PR tries to authenticate using password as token at first, together with verifying username, and if that fails, it will try to fallback to try authenticate using username as token.
=> auth: enable authentication by token from password

internal/db/webhook.go, internal/route/lfs/basic_test.go, internal/route/lfs/batch_test.go, internal/route/lfs/route_test.go, internal/route/repo/setting.go, internal/route/user/setting.go
=> refactor: replace `ioutil.ReadAll` with `io.ReadAll`

templates/org/create.tmpl, templates/org/team/new.tmpl, templates/repo/create.tmpl, templates/repo/migrate.tmpl, templates/repo/pulls/fork.tmpl
Port of go-gitea/gitea#21381
There's no need for a cancel button, just leave the page.
=> ui: remove useless "Cancel" buttons

CHANGELOG.md, internal/context/api.go, internal/route/api/v1/api.go, internal/route/api/v1/repo/contents.go
This pull request tries to close #5967 and add PUT content endpoint to gogs.
Maybe some things should be moved along and added to `git-gogs-client` package instead. I wasn't sure where to put types I needed during that development.
I do need someone to help me figure out how to properly add missing values. This is what I found on [github API reference](https://docs.github.com/en/rest/repos/contents#about-the-repository-contents-api) and I tried to follow it but had hard time figure out how to populate things like content's `url`, `html_url`, `git_url`, `download_url` and so on. I also couldn't figure out commit object's `node_id`, `tree`, `parents`. Let me know if there's any existing logic I could use to get those based on say git commit.
```json
{
"content": {
"name": "hello.txt", …
```
=> api: support put content

docs/dev/release/release_new_version.md
=> release: update playbook

internal/db/repo_editor.go, internal/route/repo/editor.go
=> chore(db): remove unused field

docs/dev/database_schema.md, internal/db/backup_test.go, internal/db/db.go, internal/db/follows.go, internal/db/follows_test.go, internal/db/main_test.go, internal/db/models.go, internal/db/testdata/backup/Follow.golden.json, internal/db/user.go, internal/db/users.go, internal/db/users_test.go, internal/dbtest/dbtest.go, internal/route/api/v1/user/follower.go, internal/route/lfs/mocks_test.go, internal/route/user/profile.go
=> refactor(db): migrate `Follow` off `user.go`

internal/db/pull.go, internal/db/repo.go, internal/db/repo_editor.go, internal/db/user.go, internal/db/users.go, internal/db/wiki.go, internal/route/admin/users.go, internal/route/api/v1/admin/user.go, internal/route/repo/webhook.go, internal/route/user/auth.go, internal/route/user/setting.go, internal/userutil/userutil.go, internal/userutil/userutil_test.go
=> refactor(db): migrate password methods off `user.go`

internal/db/repo.go, internal/db/two_factors.go, internal/db/two_factors_test.go, internal/db/user.go, internal/db/users.go, internal/route/api/v1/repo/repo.go, internal/route/lfs/mocks_test.go, internal/route/lfs/route.go, internal/route/lfs/route_test.go, internal/route/repo/http.go, internal/route/repo/issue.go, internal/route/repo/pull.go, internal/route/user/auth.go, internal/route/user/setting.go
=> refactor(db): migrate perms methods off `user.go`

internal/db/access_tokens_test.go, internal/db/actions_test.go, internal/db/login_sources.go, internal/db/login_sources_test.go, internal/db/repos_test.go, internal/db/two_factors_test.go, internal/db/users_test.go
=> test(db): add missing tests

internal/db/access_tokens_test.go, internal/db/actions_test.go, internal/db/db.go, internal/db/follows.go, internal/db/follows_test.go, internal/db/lfs_test.go, internal/db/login_sources_test.go, internal/db/org.go, internal/db/org_users.go, internal/db/org_users_test.go, internal/db/perms_test.go, internal/db/repos_test.go, internal/db/two_factors_test.go, internal/db/user.go, internal/db/users.go, internal/db/users_test.go, internal/db/watches_test.go, internal/route/user/home.go
=> refactor(db): migrate methods off `user.go`

internal/db/db.go, internal/db/org.go, internal/db/org_users_test.go, internal/db/orgs.go, internal/db/orgs_test.go, internal/db/user.go, internal/db/users.go, internal/dbutil/logger.go, internal/dbutil/string.go, internal/dbutil/string_test.go, internal/route/api/v1/org/org.go, internal/route/repo/pull.go, internal/route/user/home.go, templates/user/dashboard/dashboard.tmpl
=> refactor(db): migrate methods off `user.go` and `org.go` (#7219)

internal/conf/mocks.go, internal/db/pull.go, internal/db/repo.go, internal/db/user.go, internal/db/users.go, internal/db/users_test.go, internal/repoutil/repoutil.go, internal/repoutil/repoutil_test.go, internal/route/lfs/mocks_test.go, internal/route/org/setting.go, internal/route/user/setting.go
=> refactor(db): migrate `ChangeUsername` off `user.go`

internal/db/user.go, internal/db/users.go, internal/db/users_test.go
=> fix(db): update `user.updated_unix` upon changing username

internal/db/email_addresses.go, internal/db/email_addresses_test.go, internal/db/org.go, internal/db/user.go, internal/db/users.go, internal/db/users_test.go, internal/form/user.go, internal/route/lfs/mocks_test.go, internal/route/org/setting.go, internal/route/repo/setting.go, internal/route/user/auth.go, internal/route/user/setting.go, internal/strutil/strutil.go, internal/strutil/strutil_test.go, internal/tool/tool.go, templates/user/settings/profile.tmpl
=> refactor(db): add `Users.Update`

internal/auth/auth.go, internal/db/access_tokens.go, internal/db/email_addresses.go, internal/db/users.go, internal/gitutil/error.go, internal/route/lfs/route.go, internal/route/org/setting.go, internal/route/repo/http.go, internal/route/repo/view.go, internal/route/user/auth.go
=> chore: consistently use `errors.Cause` for identifying error types

CHANGELOG.md, internal/db/repo.go, internal/db/user.go, internal/db/user_mail.go, internal/db/users.go, internal/db/users_test.go, internal/email/message.go, internal/form/user.go, internal/route/admin/users.go, internal/route/api/v1/admin/user.go, internal/route/api/v1/org/org.go, internal/route/org/setting.go, internal/route/repo/setting.go, internal/route/user/auth.go, internal/route/user/setting.go
=> refactor(db): migrate `UpdateUser` off `user.go`

internal/db/issue.go
=> chore: fix typo in docstring

README.md
=> README: update VPS sponsor

README.md
=> README: update sponsor link

CHANGELOG.md, internal/cmd/backup.go, internal/cmd/restore.go
Link to the issue: fixes https://github.com/gogs/gogs/issues/6785
=> fix(backup): skip "data" in the custom directory

CHANGELOG.md, go.mod, go.sum, templates/repo/view_list.tmpl
Link to the issue: fixes https://github.com/gogs/gogs/issues/6436
1. Follow steps described in https://github.com/gogs/gogs/issues/6436#issuecomment-1375885089 (i.e. adding a Git repository without adding a submodule).
2. Visit the repository:
=> fix(repo): be tolerant to implicit submodules

CHANGELOG.md, internal/db/migrations/migrations.go, internal/db/migrations/v20.go, internal/db/migrations/v20_test.go, internal/db/migrations/v21.go, internal/db/migrations/v21_test.go
Link to the issue: fixes https://github.com/gogs/gogs/issues/7125
=> fix(migration): skip v20 if column `sha256` already exists

internal/dbtest/dbtest.go
=> dbtest: properly close test connection

internal/database/access_tokens_test.go, internal/database/actions_test.go, internal/database/attachment.go, internal/database/comment.go, internal/database/database.go, internal/database/issue_label.go, internal/database/lfs_test.go, internal/database/login_sources_test.go, internal/database/main_test.go, internal/database/milestone.go, internal/database/mirror.go, internal/database/notices_test.go, internal/database/org_team.go, internal/database/orgs_test.go, internal/database/perms_test.go, internal/database/public_keys_test.go, internal/database/release.go, internal/database/repos_test.go, internal/database/ssh_key.go, internal/database/two_factors_test.go, internal/database/users_test.go, internal/database/webhook.go
=> database: use all tables to setup test suite

internal/database/database.go, internal/database/mirror.go, internal/database/notices.go, internal/database/notices_test.go, internal/database/repo.go, internal/route/admin/notice.go
=> all: unwrap `database.NoticesStore` interface

internal/database/database.go, internal/database/models.go, internal/route/install.go
Fixes https://github.com/gogs/gogs/issues/7698
CI
=> database: set `Handle` direcetly during initialization

internal/cmd/serv.go, internal/context/repo.go, internal/database/database.go, internal/database/mocks.go, internal/database/permissions.go, internal/database/permissions_test.go, internal/database/repo.go, internal/database/repo_branch.go, internal/database/repos_test.go, internal/database/ssh_key.go, internal/route/api/v1/api.go, internal/route/api/v1/repo/repo.go, internal/route/lfs/mocks_test.go, internal/route/lfs/route.go, internal/route/lfs/route_test.go, internal/route/lfs/store.go, internal/route/repo/http.go, internal/route/repo/issue.go, internal/route/repo/pull.go, mockgen.yaml
=> all: unwrap `database.PermissionsStore` interface

internal/database/database.go, internal/database/public_keys.go, internal/database/public_keys_test.go, internal/database/users.go, internal/database/users_test.go
=> all: unwrap `database.PublicKeysStore` interface

internal/context/go_get.go, internal/context/repo.go, internal/database/actions.go, internal/database/actions_test.go, internal/database/database.go, internal/database/mocks.go, internal/database/repositories.go, internal/database/repositories_test.go, internal/database/users_test.go, internal/route/api/v1/api.go, internal/route/api/v1/repo/repo.go, internal/route/lfs/mocks_test.go, internal/route/lfs/route.go, internal/route/lfs/route_test.go, internal/route/lfs/store.go, internal/route/repo/http.go, internal/route/repo/issue.go, internal/route/repo/store.go, internal/route/repo/tasks.go, internal/route/user/home.go, mockgen.yaml
=> all: unwrap `database.RepositoriesStore` interface

internal/database/database.go, internal/database/mocks.go, internal/database/two_factors.go, internal/database/two_factors_test.go, internal/route/lfs/mocks_test.go, internal/route/lfs/route.go, internal/route/lfs/route_test.go, internal/route/lfs/store.go, internal/route/repo/http.go, internal/route/repo/store.go, internal/route/user/auth.go, internal/route/user/setting.go, mockgen.yaml
=> all: unwrap `database.TwoFactorsStore` interface

internal/cmd/import.go
Remove duplicate error checking and fix typo error message on cmd/import.go
=> chore: remove duplicate error and fix typo error message

internal/route/repo/editor.go
Link to the issue: https://github.com/gogs/gogs/issues/7582
Manually tested
=> repo/editor: disallow editing symlink while changing file name

internal/database/repo_editor.go, internal/pathutil/pathutil.go, internal/route/api/v1/repo/contents.go, internal/route/repo/editor.go, internal/route/repo/http.go
Link to the issue: closes https://github.com/gogs/gogs/issues/7582
CI
=> api: clean file path for updating repo contents

internal/database/ssh_key.go, internal/ssh/ssh.go
Fixes https://github.com/gogs/gogs/security/advisories/GHSA-vm62-9jw3-c8w3
Manually tested
=> ssh: make `env` command a passthrough

internal/database/repo_editor.go
Fixes https://github.com/gogs/gogs/security/advisories/GHSA-ccqv-43vm-4f3w
Tested manually
=> repo: prevent preview and delete files in `.git` directories

CHANGELOG.md
Part of https://github.com/gogs/gogs/issues/7873
=> release: cut CHANGELOG entries for 0.13.1

docker/start.sh
Link to the issue: https://github.com/gogs/gogs/issues/7864
=> Dockerfile: fix up outdated s6-svscan path
